//! Protocol version & decode hardening tests.
//!
//! The wire protocol does NOT carry an explicit numeric version field; the
//! shape of the JSON tagged enum (`{"type": "HELLO" | "HAVE" | ...}`) *is*
//! the version. These tests pin that implicit v1 contract so any accidental
//! rename, removal, or breaking change is caught immediately.
//!
//! Beta-bonus coverage:
//! - Pin the set of supported message type tags (regression alarm).
//! - Confirm older payload shapes (v1) still decode (back-compat lock).
//! - Confirm unknown / future message types yield a clean error (no panic).
//! - Confirm encode → decode is bit-identity for every variant.
//! - Confirm truncated / partial JSON returns Err (no out-of-bounds read).

use copypaste_sync::{Message, WireItem};

/// Protocol "version" surface: the canonical set of message type tags
/// emitted by `Message`'s serde Serialize impl. If this list changes, every
/// peer on the network has to be updated — pin it.
const PROTOCOL_V1_TAGS: &[&str] = &["HELLO", "HAVE", "WANT", "ITEMS", "DONE"];

fn tag_of(msg: &Message) -> String {
    let v: serde_json::Value = serde_json::to_value(msg).expect("serialize");
    v.get("type")
        .and_then(|t| t.as_str())
        .expect("every message must have a string 'type' tag")
        .to_string()
}

fn sample_wire_item() -> WireItem {
    WireItem {
        id: "item-uuid-0001".to_string(),
        item_id: "secondary-uuid-0001".to_string(),
        content_type: "text".to_string(),
        content: Some(b"hello".to_vec()),
        content_nonce: Some(vec![7u8; 24]),
        blob_ref: None,
        is_sensitive: false,
        lamport_ts: 123,
        wall_time: 1_700_000_000_000,
        expires_at: Some(1_800_000_000_000),
        app_bundle_id: Some("com.example.app".to_string()),
        origin_device_id: "device-uuid-aaaa".to_string(),
    }
}

// ---------------------------------------------------------------------------
// 1. Current "version" — pin the set of supported message type tags.
// ---------------------------------------------------------------------------

#[test]
fn current_version_constant_matches_expected() {
    // Build one of every variant and collect their serialized type tags.
    let all = [
        Message::Hello {
            device_id: "d".into(),
            clock: 0,
            item_count: 0,
        },
        Message::Have { items: vec![] },
        Message::Want { item_ids: vec![] },
        Message::Items { items: vec![] },
        Message::Done,
    ];

    let actual: Vec<String> = all.iter().map(tag_of).collect();

    assert_eq!(
        actual,
        PROTOCOL_V1_TAGS,
        "Protocol v1 message type surface changed. If this was intentional, \
         bump the protocol version, update PROTOCOL_V1_TAGS, and coordinate \
         a network-wide rollout."
    );
}

// ---------------------------------------------------------------------------
// 2. Back-compat — a "v1" payload (the shape we ship today) still decodes.
//    This locks the schema: renaming a field on Message would break this.
// ---------------------------------------------------------------------------

#[test]
fn decode_v1_payload_still_works() {
    // Hand-written JSON in the exact v1 shape — NOT generated by serde.
    // If a field is renamed in src/, this test fails loud.
    let v1_hello = br#"{"type":"HELLO","device_id":"abc","clock":7,"item_count":3}"#;
    let decoded = Message::decode(v1_hello).expect("v1 HELLO must still decode");
    match decoded {
        Message::Hello {
            device_id,
            clock,
            item_count,
        } => {
            assert_eq!(device_id, "abc");
            assert_eq!(clock, 7);
            assert_eq!(item_count, 3);
        }
        other => panic!("expected Hello, got {other:?}"),
    }

    let v1_done = br#"{"type":"DONE"}"#;
    assert!(matches!(
        Message::decode(v1_done).expect("v1 DONE must still decode"),
        Message::Done
    ));

    let v1_want = br#"{"type":"WANT","item_ids":["x","y"]}"#;
    match Message::decode(v1_want).expect("v1 WANT must still decode") {
        Message::Want { item_ids } => assert_eq!(item_ids, vec!["x", "y"]),
        other => panic!("expected Want, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// 3. Unknown type tag — must return Err, not panic.
//    Forward-compat: a peer running a NEWER protocol sends a tag we don't
//    know. We must reject cleanly so the sync engine can decide what to do.
// ---------------------------------------------------------------------------

#[test]
fn decode_unknown_version_returns_specific_error_not_panic() {
    // Future / unknown message type — should be a clean serde error.
    let future = br#"{"type":"FUTURE_HANDSHAKE_V2","payload":{"foo":42}}"#;
    let result = Message::decode(future);
    assert!(
        result.is_err(),
        "unknown message type must be rejected, got Ok({:?})",
        result.ok()
    );

    // Plausible "version = 0xFF" style — a totally unknown tag.
    let unknown_tag = br#"{"type":"FF"}"#;
    let result = Message::decode(unknown_tag);
    assert!(
        result.is_err(),
        "unknown message tag 'FF' must be rejected"
    );

    // Missing the discriminator entirely.
    let no_type = br#"{"device_id":"x","clock":1,"item_count":0}"#;
    let result = Message::decode(no_type);
    assert!(
        result.is_err(),
        "payload without 'type' discriminator must be rejected"
    );
}

// ---------------------------------------------------------------------------
// 4. Encode → decode identity for every variant, including a full WireItem.
// ---------------------------------------------------------------------------

#[test]
fn encode_then_decode_roundtrip_identity() {
    let messages = vec![
        Message::Hello {
            device_id: "device-uuid-roundtrip".to_string(),
            clock: u64::MAX,
            item_count: 0,
        },
        Message::Have {
            items: vec![
                ("id-a".to_string(), 0),
                ("id-b".to_string(), i64::MAX),
                ("id-c".to_string(), -1),
            ],
        },
        Message::Want {
            item_ids: vec!["w1".to_string(), "w2".to_string()],
        },
        Message::Items {
            items: vec![sample_wire_item()],
        },
        Message::Done,
    ];

    for original in messages {
        let framed = original.encode().expect("encode");

        // Frame format: [u32 LE length][JSON bytes]
        assert!(framed.len() >= 4, "frame must include 4-byte prefix");
        let claimed_len =
            u32::from_le_bytes(framed[..4].try_into().expect("4 bytes")) as usize;
        assert_eq!(
            claimed_len,
            framed.len() - 4,
            "length prefix must match JSON body length"
        );

        let decoded = Message::decode(&framed[4..]).expect("decode");
        assert_eq!(
            decoded, original,
            "roundtrip identity failed for {original:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// 5. Truncated / malformed payloads — must Err, never panic or OOB-read.
// ---------------------------------------------------------------------------

#[test]
fn truncated_payload_returns_error() {
    // Build a real frame, then chop pieces off the JSON body.
    let msg = Message::Items {
        items: vec![sample_wire_item()],
    };
    let framed = msg.encode().expect("encode");
    let body = &framed[4..];

    // Empty body.
    assert!(
        Message::decode(&[]).is_err(),
        "empty payload must return Err"
    );

    // First byte only — definitely not valid JSON.
    assert!(
        Message::decode(&body[..1]).is_err(),
        "single-byte payload must return Err"
    );

    // Half of the body — invalid JSON / truncated string.
    let half = body.len() / 2;
    assert!(
        Message::decode(&body[..half]).is_err(),
        "half-truncated payload must return Err"
    );

    // One byte short — almost-but-not-quite complete JSON.
    assert!(
        Message::decode(&body[..body.len() - 1]).is_err(),
        "one-byte-short payload must return Err"
    );

    // Garbage that is not JSON at all.
    assert!(
        Message::decode(b"\xff\xfe\xfd\xfc").is_err(),
        "binary garbage must return Err"
    );

    // Valid JSON but wrong shape (an array, not an object).
    assert!(
        Message::decode(b"[1,2,3]").is_err(),
        "wrong-shape JSON must return Err"
    );
}
