//! P2P Phase 1 — network bootstrap PAKE pairing, end-to-end over TCP/TLS.
//!
//! This test spawns TWO real, fully-isolated `copypaste-daemon` subprocesses
//! with the P2P subsystem enabled (`COPYPASTE_P2P=1`, `COPYPASTE_EPHEMERAL_KEY=1`):
//!
//! - Daemon A is the **responder**: it generates a pairing QR. With P2P
//!   enabled, generating the QR also spins up an ephemeral, unauthenticated
//!   bootstrap TLS listener and embeds its `host:port` in the QR's `addr_hint`.
//! - Daemon B is the **initiator**: it accepts the scanned QR
//!   (`pair_accept_qr {"qr": ...}`), dials A's bootstrap address over TLS
//!   (no cert pinning), and runs the PAKE initiator handshake over that real
//!   network socket.
//!
//! Success is asserted from B's IPC response: the network branch only returns
//! `ok: true` when the OPAQUE PAKE handshake completes on BOTH endpoints (the
//! responder must finish for the initiator's final message to be consumed and
//! for the shared session key to exist). The returned `peer_fingerprint` is
//! cross-checked against A's actual cert fingerprint, proving the fingerprint
//! exchange over the bootstrap channel matched the cert A presented in TLS.
//!
//! This is NOT a single-process fake: A and B are separate OS processes, and
//! the PAKE messages + fingerprints traverse a real loopback TCP/TLS connection.

#[path = "support/mod.rs"]
mod support;

use support::Daemon;

/// Strip the colons from a user-facing `XX:XX:...` fingerprint to get the
/// canonical lowercase hex the mTLS layer / bootstrap channel report.
fn canonical(fp: &str) -> String {
    fp.replace(':', "").to_lowercase()
}

#[test]
fn two_daemons_complete_pake_over_network_bootstrap() {
    // Both daemons run with P2P enabled so they have a live mTLS cert and the
    // bootstrap pairing channel.
    let daemon_a = Daemon::spawn_with_p2p();
    let daemon_b = Daemon::spawn_with_p2p();

    // A's advertised (colon-hex) cert fingerprint — what the QR carries and
    // what B should learn over the bootstrap channel (in canonical form).
    let fp_resp = daemon_a.request(r#"{"id":"fa","method":"get_own_fingerprint","params":{}}"#);
    assert_eq!(
        fp_resp["ok"], true,
        "A get_own_fingerprint failed: {fp_resp}"
    );
    let fp_a_display = fp_resp["data"]["fingerprint"]
        .as_str()
        .expect("A fingerprint string")
        .to_string();
    let fp_a_canonical = canonical(&fp_a_display);

    // Step 1 — A generates a QR. With P2P on, this binds A's bootstrap TLS
    // listener and embeds its host:port in addr_hint.
    let qr_resp = daemon_a.request(r#"{"id":"qa","method":"pair_generate_qr","params":{}}"#);
    assert_eq!(qr_resp["ok"], true, "pair_generate_qr failed: {qr_resp}");
    let qr = qr_resp["data"]["qr"]
        .as_str()
        .expect("QR string in response")
        .to_string();
    assert!(qr.starts_with("CPPAIR1."), "QR must use the v1 magic: {qr}");

    // The QR must carry a non-empty addr_hint (the bootstrap listener address).
    // addr_hint is the final field; it contains ':' and dotted IP octets, so we
    // assert the loopback host:port marker is present rather than re-splitting on
    // '.' (which would also split the IP).
    assert!(
        qr.contains("127.0.0.1:"),
        "QR addr_hint must point at A's bootstrap listener, got QR: {qr}"
    );

    // Step 2 — B accepts the QR over the NETWORK: decode, dial A's addr_hint
    // over TLS, run the PAKE initiator. This single IPC call drives the whole
    // network handshake; it returns ok only if PAKE completed on both ends.
    let accept_body = serde_json::json!({
        "id": "qb",
        "method": "pair_accept_qr",
        "params": { "qr": qr },
    })
    .to_string();
    let accept_resp = daemon_b.request(&accept_body);

    assert_eq!(
        accept_resp["ok"], true,
        "network PAKE pairing must succeed end-to-end, got: {accept_resp}"
    );

    // B learned A's real cert fingerprint over the bootstrap channel, and it
    // matches the cert A actually presented (and advertised in the QR).
    let peer_fp = accept_resp["data"]["peer_fingerprint"]
        .as_str()
        .expect("network accept must report the peer fingerprint");
    assert_eq!(
        peer_fp, fp_a_canonical,
        "B's PAKE-confirmed peer fingerprint must equal A's cert fingerprint"
    );
}

/// Wrong/garbage QR token: if B dials with a QR whose token does not match the
/// one A's bootstrap responder registered, the PAKE handshake must fail and the
/// network accept must report an error — never a false-positive pairing.
///
/// We simulate a mismatch by having B accept a QR generated by A but pointed at
/// a *second* generation's listener with a different token: regenerating on A
/// replaces the active bootstrap responder/token, so the QR from the first
/// generation now targets a stale port. The cleaner deterministic check is that
/// a structurally-valid QR with an unreachable addr_hint fails fast.
#[test]
fn network_pairing_fails_on_unreachable_addr_hint() {
    let daemon_b = Daemon::spawn_with_p2p();

    // Build a syntactically valid QR by hand whose addr_hint points at a closed
    // loopback port (nothing is listening), so the bootstrap dial must fail.
    // Reuse B's own fingerprint format for the fingerprint field (any valid
    // colon-hex 32-byte fingerprint works; pairing fails at the dial/PAKE step).
    let fp_resp = daemon_b.request(r#"{"id":"fb","method":"get_own_fingerprint","params":{}}"#);
    let fp_display = fp_resp["data"]["fingerprint"]
        .as_str()
        .expect("B fingerprint")
        .to_string();

    // A fresh QR from a throwaway daemon gives us a real token + wire shape;
    // we then rewrite its addr_hint to an unreachable port.
    let daemon_tmp = Daemon::spawn_with_p2p();
    let qr_resp = daemon_tmp.request(r#"{"id":"qt","method":"pair_generate_qr","params":{}}"#);
    let qr = qr_resp["data"]["qr"].as_str().expect("tmp QR").to_string();

    // Replace the trailing addr_hint (the real `127.0.0.1:<port>` field) with an
    // almost-certainly-closed port so the bootstrap dial is refused. The addr
    // marker `127.0.0.1:` appears only in the addr_hint field (the fingerprint
    // field is colon-hex, never dotted-quad), so splitting there is unambiguous.
    let marker_pos = qr.rfind("127.0.0.1:").expect("tmp QR must carry addr_hint");
    let bad_qr = format!("{}127.0.0.1:1", &qr[..marker_pos]);
    let _ = &fp_display;

    let accept_body = serde_json::json!({
        "id": "qbad",
        "method": "pair_accept_qr",
        "params": { "qr": bad_qr },
    })
    .to_string();
    let accept_resp = daemon_b.request(&accept_body);

    assert_eq!(
        accept_resp["ok"], false,
        "pairing against an unreachable bootstrap addr must fail, got: {accept_resp}"
    );
}
