// ESLint flat config (eslint.config.js) — requires ESLint >=8.57 / 9.x.
//
// Rule philosophy (CopyPaste-q3pe):
// - @typescript-eslint/recommended + react-recommended as baselines.
// - `no-undef` is disabled for TS files: the compiler already catches undefined
//   identifiers, and the rule produces false positives for global types.
// - `react-hooks/exhaustive-deps` and `react-refresh/only-export-components`
//   are set to "warn" so existing code is flagged but not blocked.
// - `react/no-danger` is set to "warn" (not error): dangerouslySetInnerHTML
//   in DevicesView is used for QR SVG generated by the `qrcode` Rust library
//   (not user-controlled input) and is documented as safe at the call site.
// - A small set of correctness rules are "error" to catch real bugs in new code
//   without flooding the existing codebase.
// - Stylistic/formatting rules are excluded; Vite + tsc cover those.
// - Type-aware lint rules (parserOptions.project) are excluded: the
//   tsconfig.json excludes test files, which would cause fatal parse errors.
//   tsc enforces types via `pnpm build`.

import js from "@eslint/js";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import reactPlugin from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";

export default [
  // ── ignore patterns ──────────────────────────────────────────────────────
  {
    ignores: [
      "dist/**",
      "src-tauri/**",        // Rust-managed; not linted here
      "node_modules/**",
      "coverage/**",
      "scripts/**",          // Node.js helper scripts, not the app bundle
      "*.config.js",         // vite/postcss/tailwind configs — often CommonJS
      "*.config.ts",
    ],
  },

  // ── base JS recommended — as a starting point, then TS rules override ────
  js.configs.recommended,

  // ── TypeScript source files (app + test) ─────────────────────────────────
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        // No `project` / `projectService` — avoids fatal parse errors on test
        // files excluded from tsconfig.json. Type-checking is done by `pnpm build` (tsc).
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
      "react": reactPlugin,
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    settings: {
      react: {
        // Suppress "React version not specified" warning. We use React 19.
        version: "detect",
      },
    },
    rules: {
      // TypeScript recommended (non-type-checked) — replaces js.configs.recommended
      // rules that overlap.
      ...tsPlugin.configs["recommended"].rules,

      // `no-undef` is redundant in TypeScript projects: the TS compiler already
      // catches undefined identifiers, and the ESLint rule generates false
      // positives for global types (e.g. `fetch`, `ResizeObserver`, `vi`).
      "no-undef": "off",

      // Prefer the TS-aware unused-vars rule; disable the base rule to avoid
      // double-reporting.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { varsIgnorePattern: "^_", argsIgnorePattern: "^_" },
      ],

      // Catch explicit `any` — real bug signal. New code must not add `any`.
      "@typescript-eslint/no-explicit-any": "error",

      // console.log in production components is noisy; allow warn/error.
      "no-console": ["warn", { allow: ["warn", "error"] }],

      // React Hooks rules — exhaustive-deps set to warn because existing
      // components have deliberate omissions with documented reasons.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",

      // React Refresh: components exported alongside non-component values are
      // warn-level so existing utility+component colocations are not blocked.
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],

      // dangerouslySetInnerHTML: warn rather than error. The one usage in
      // DevicesView (QR SVG from the `qrcode` Rust library) is server-generated
      // and does not embed user input. Warn so new usages are reviewed.
      "react/no-danger": "warn",

      // Stylistic rules — downgraded to warn so existing code isn't blocked.
      "@typescript-eslint/no-inferrable-types": "warn",
    },
  },

  // ── Test files — additional globals + relaxed rules ───────────────────────
  {
    files: ["src/**/*.test.{ts,tsx}"],
    languageOptions: {
      globals: {
        // Vitest test globals (describe, it, expect, vi, beforeEach, …)
        // vitest exposes these as global when `globals: true` is set in
        // vitest.config.ts — treat them as known globals here so no-undef
        // (if re-enabled) and the TS parser don't complain.
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        vi: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
      },
    },
    rules: {
      // Test code frequently uses `any` for mock types.
      "@typescript-eslint/no-explicit-any": "warn",
      // Test helper variables are sometimes imported but only used in a subset
      // of test cases or left intentionally for documentary purposes.
      "@typescript-eslint/no-unused-vars": "warn",
      // Console output is expected in tests.
      "no-console": "off",
    },
  },
];
