import {
  TAURI_EVENTS,
  TAURI_EVENT_NAMES,
  type TauriEventName,
} from "@/generated/ipc";

export const EVENT_CHANGED = TAURI_EVENTS.COPYPASTE_CHANGED;
export const EVENT_PUSH_STATE = TAURI_EVENTS.COPYPASTE_PUSH_STATE;
export const EVENT_CAPTURED = TAURI_EVENTS.COPYPASTE_CAPTURED;
export const EVENT_CAPTURE_STATE = TAURI_EVENTS.COPYPASTE_CAPTURE_STATE;
export const EVENT_PRIVATE_MODE_CHANGED = TAURI_EVENTS.PRIVATE_MODE_CHANGED;
export const EVENT_AUTOSTART_CHANGED = TAURI_EVENTS.AUTOSTART_CHANGED;
export const EVENT_OPEN_SETTINGS = TAURI_EVENTS.OPEN_SETTINGS;

export { TAURI_EVENT_NAMES };

type AssertNever<T extends never> = T;
export type TauriEventNamesAreComplete = AssertNever<
  Exclude<TauriEventName, (typeof TAURI_EVENT_NAMES)[number]>
>;
