package com.copypaste.android

// Placeholder for UniFFI-generated bindings
// Generated by: ./scripts/build-android.sh
// Source: crates/copypaste-android/uniffi/copypaste_android.udl

external fun encryptText(bytes: ByteArray, key: ByteArray): EncryptedBlob
external fun decryptText(ciphertext: ByteArray, nonce: ByteArray, key: ByteArray): ByteArray
external fun isSensitive(text: String): Boolean
external fun sensitiveKind(text: String): String?
external fun openDatabase(path: String): Long
external fun closeDatabase(handle: Long)

data class EncryptedBlob(val nonce: ByteArray, val ciphertext: ByteArray)
