cask "copypaste" do
  version "0.2.0-beta.0"
  sha256 :no_check # TODO(post-tag): real sha256 generated by scripts/release/gen-cask.sh

  url "https://github.com/USER/CopyPaste/releases/download/v#{version}/CopyPaste.dmg",
      verified: "github.com/USER/CopyPaste/"
  name "CopyPaste"
  desc "Encrypted clipboard manager with end-to-end sync"
  homepage "https://github.com/USER/CopyPaste"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates false
  depends_on macos: :sonoma

  app "CopyPaste.app"

  postflight do
    # Strip quarantine (ad-hoc signed builds, no Apple Developer ID)
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/CopyPaste.app"]
    # Load launchd plist if it exists
    plist = Pathname.new("#{Dir.home}/Library/LaunchAgents/com.copypaste.daemon.plist")
    system_command "/bin/launchctl", args: ["load", "-w", plist.to_s] if plist.exist?
  end

  uninstall launchctl: "com.copypaste.daemon",
            delete:    "#{appdir}/CopyPaste.app"

  zap trash: [
    "~/Library/Application Support/copypaste",
    "~/Library/Caches/com.copypaste.daemon",
    "~/Library/LaunchAgents/com.copypaste.daemon.plist",
    "~/Library/Logs/copypaste",
  ]

  caveats <<~EOS
    CopyPaste uses ad-hoc signing (no Apple Developer ID). Homebrew strips
    the quarantine attribute on install, so you should not see a Gatekeeper
    warning.

    The daemon runs as a LaunchAgent (#{ENV.fetch("USER", "current")} user). Logs at:
      ~/Library/Logs/copypaste/

    First run starts the daemon automatically. To stop:
      launchctl unload ~/Library/LaunchAgents/com.copypaste.daemon.plist
  EOS
end
