import type { ComponentType } from "react";
import {
    AppWindow,
    ArrowDown,
    ArrowLeft,
    ArrowClockwise,
    ArrowCounterClockwise,
    ArrowsLeftRight,
    ArrowUp,
    BatteryCharging,
    BracketsCurly,
    CaretDown,
    CaretRight,
    ChatCircleDots,
    Check,
    CheckCircle,
    CheckSquare,
    Circle,
    ClipboardText,
    Cloud,
    CloudSlash,
    Code,
    Compass,
    Copy,
    DownloadSimple,
    CornersOut,
    DeviceMobile,
    DeviceTablet,
    Devices,
    DotsThree,
    Eye,
    EyeSlash,
    File,
    FileImage,
    FileText,
    FileX,
    FolderSimple,
    GearSix,
    Globe,
    HardDrive,
    Hash,
    Image,
    ImageBroken,
    Info,
    Key,
    Keyboard,
    LinkSimple,
    ListBullets,
    Laptop,
    LockKey,
    MagnifyingGlass,
    Monitor,
    Palette,
    PaperPlaneTilt,
    Pause,
    PencilSimple,
    Play,
    PushPin,
    PushPinSlash,
    ShieldWarning,
    ShieldCheck,
    ShieldSlash,
    SpinnerGap,
    Stethoscope,
    Plugs,
    Plus,
    QrCode,
    Scan,
    SlidersHorizontal,
    UploadSimple,
    WifiSlash,
    TerminalWindow,
    TextT,
    Trash,
    Tray,
    WarningCircle,
    X,
    XCircle,
    type IconProps as PhosphorIconProps,
} from "@phosphor-icons/react";
import { cn } from "@/lib/cn";
import styles from "./icon.module.css";

const icons = {
    app: AppWindow,
    braces: BracketsCurly,
    caretDown: CaretDown,
    caretRight: CaretRight,
    check: Check,
    selectAll: CheckSquare,
    code: Code,
    compass: Compass,
    copy: Copy,
    cloud: Cloud,
    cloudOff: CloudSlash,
    devices: Devices,
    expand: CornersOut,
    file: File,
    fileImage: FileImage,
    fileText: FileText,
    fileWarning: FileX,
    folder: FolderSimple,
    globe: Globe,
    hash: Hash,
    image: Image,
    imageBroken: ImageBroken,
    info: Info,
    key: Key,
    keyboard: Keyboard,
    library: ClipboardText,
    link: LinkSimple,
    list: ListBullets,
    lock: LockKey,
    mail: PaperPlaneTilt,
    login: CaretRight,
    logout: CaretRight,
    back: ArrowLeft,
    github: LinkSimple,
    sun: Palette,
    messages: ChatCircleDots,
    mobile: DeviceMobile,
    tablet: DeviceTablet,
    monitor: Monitor,
    more: DotsThree,
    palette: Palette,
    pause: Pause,
    pin: PushPin,
    unpin: PushPinSlash,
    search: MagnifyingGlass,
    sensitive: ShieldWarning,
    settings: GearSix,
    terminal: TerminalWindow,
    text: TextT,
    trash: Trash,
    tray: Tray,
    unknown: WarningCircle,
    eye: Eye,
    eyeOff: EyeSlash,
    close: X,
    xCircle: XCircle,
    alert: WarningCircle,
    battery: BatteryCharging,
    checkCircle: CheckCircle,
    circle: Circle,
    download: DownloadSimple,
    laptop: Laptop,
    pencil: PencilSimple,
    play: Play,
    plus: Plus,
    plug: Plugs,
    qrCode: QrCode,
    refresh: ArrowClockwise,
    reset: ArrowCounterClockwise,
    scan: Scan,
    sliders: SlidersHorizontal,
    sortAscending: ArrowUp,
    sortDescending: ArrowDown,
    searchX: MagnifyingGlass,
    shieldCheck: ShieldCheck,
    shieldOff: ShieldSlash,
    shieldX: ShieldWarning,
    spinner: SpinnerGap,
    stethoscope: Stethoscope,
    storage: HardDrive,
    transfer: ArrowsLeftRight,
    upload: UploadSimple,
    wifiOff: WifiSlash,
} satisfies Record<string, ComponentType<PhosphorIconProps>>;

export type IconName = keyof typeof icons;
export type IconSize = "xs" | "sm" | "md" | "lg";

export function iconComponent(name: IconName) {
    return icons[name];
}

interface IconProps {
    name: IconName;
    size?: IconSize;
    weight?: PhosphorIconProps["weight"];
    label?: string;
    className?: string;
    "aria-hidden"?: boolean | "true" | "false";
}

export function Icon({
    name,
    size = "sm",
    weight = "bold",
    label,
    className,
}: IconProps) {
    const Glyph = icons[name];
    return (
        <span
            className={cn(styles.icon, styles[size], className)}
            role={label ? "img" : undefined}
            aria-label={label}
            aria-hidden={label ? undefined : true}
        >
            <Glyph size="1em" weight={weight} />
        </span>
    );
}
