use std::fmt::Write;

use anyhow::Result;
use serde::Serialize;

use crate::schema::{Allowlist, Category, Condition, Inputs, Rule, Target, Validator};

pub fn render(inputs: &Inputs) -> Result<String> {
    let source = &inputs.selection.source;
    let mut out = String::new();
    writeln!(
        out,
        "// @generated by `cargo run -p copypaste-sensitive-rules -- generate`."
    )?;
    writeln!(
        out,
        "// Source: Gitleaks {} ({})",
        source.release, source.commit
    )?;
    writeln!(
        out,
        "// Do not edit this file; edit config/sensitive-rules.toml."
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "use super::spec::{{AllowlistCondition, AllowlistSpec, AllowlistTarget, Category, RuleSpec, Validator}};"
    )?;
    writeln!(out)?;
    constant(&mut out, "GITLEAKS_VERSION", &source.release)?;
    constant(&mut out, "GITLEAKS_COMMIT", &source.commit)?;
    constant(&mut out, "VENDORED_CONFIG_SHA256", &source.config_sha256)?;
    writeln!(out)?;
    writeln!(out, "#[cfg(test)]")?;
    writeln!(
        out,
        "pub(super) static SELECTED_GITLEAKS_RULE_IDS: &[&str] = &["
    )?;
    for id in &inputs.selected_ids {
        writeln!(out, "    {},", rust_string(id))?;
    }
    writeln!(out, "];")?;
    writeln!(out)?;
    // After `SELECTED_GITLEAKS_RULE_IDS`, not before it: check-file-size.sh
    // measures this file up to its first `#[cfg(test)]` module, and a
    // 1,446-entry table above that line would read as 1,446 source lines.
    let shared = shared_stopwords(inputs);
    for (index, words) in shared.iter().enumerate() {
        writeln!(out, "static {}: &[&str] = &[", shared_name(index))?;
        for word in words {
            writeln!(out, "    {},", rust_string(word))?;
        }
        writeln!(out, "];")?;
        writeln!(out)?;
    }
    writeln!(
        out,
        "pub(super) static GLOBAL_ALLOWLISTS: &[AllowlistSpec] = &["
    )?;
    for allowlist in &inputs.global_allowlists {
        render_allowlist(&mut out, allowlist, 1, &shared)?;
    }
    writeln!(out, "];")?;
    writeln!(out)?;
    writeln!(out, "pub(super) static RULES: &[RuleSpec] = &[")?;
    for rule in &inputs.rules {
        render_rule(&mut out, rule, &shared)?;
    }
    writeln!(out, "];")?;
    Ok(out)
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct PublicationRedaction<'a> {
    schema_version: u8,
    source: &'a str,
    patterns: Vec<PublicationPattern<'a>>,
}

#[derive(Serialize)]
struct PublicationPattern<'a> {
    rule: &'a str,
    pattern: &'a str,
}

pub fn render_publication_redaction(inputs: &Inputs) -> Result<String> {
    let patterns = inputs
        .selection
        .source
        .publication_redaction_rules
        .iter()
        .map(|name| {
            let rule = inputs
                .rules
                .iter()
                .find(|rule| rule.name == *name)
                .expect("publication rules were validated while loading inputs");
            PublicationPattern {
                rule: &rule.name,
                pattern: &rule.pattern,
            }
        })
        .collect();
    let document = PublicationRedaction {
        schema_version: 1,
        source: "config/sensitive-rules.toml",
        patterns,
    };
    Ok(format!("{}\n", serde_json::to_string_pretty(&document)?))
}

/// Stopword lists carried by more than one allowlist, in first-appearance order.
///
/// Two rules carry gitleaks' 1,446-entry placeholder vocabulary. Spelled out at
/// each site the generated table doubles, so it is emitted once and referenced
/// by name.
fn shared_stopwords(inputs: &Inputs) -> Vec<Vec<String>> {
    let all = inputs
        .global_allowlists
        .iter()
        .chain(inputs.rules.iter().flat_map(|rule| rule.allowlists.iter()))
        .map(|allowlist| &allowlist.stopwords)
        .filter(|words| !words.is_empty());
    let mut seen: Vec<&Vec<String>> = Vec::new();
    let mut shared: Vec<Vec<String>> = Vec::new();
    for words in all {
        if seen.contains(&words) {
            if !shared.contains(words) {
                shared.push(words.clone());
            }
        } else {
            seen.push(words);
        }
    }
    shared
}

fn shared_name(index: usize) -> String {
    format!("SHARED_STOPWORDS_{index}")
}

fn constant(out: &mut String, name: &str, value: &str) -> Result<()> {
    writeln!(out, "#[cfg(test)]")?;
    writeln!(
        out,
        "pub(super) const {name}: &str = {};",
        rust_string(value)
    )?;
    Ok(())
}

fn render_rule(out: &mut String, rule: &Rule, shared: &[Vec<String>]) -> Result<()> {
    writeln!(out, "    RuleSpec {{")?;
    string_slice(out, "upstream_ids", &rule.upstream_ids, 2)?;
    writeln!(out, "        name: {},", rust_string(&rule.name))?;
    writeln!(
        out,
        "        category: Category::{},",
        category(rule.category)
    )?;
    writeln!(out, "        confidence: {:?},", rule.confidence)?;
    writeln!(out, "        pattern: {},", rust_string(&rule.pattern))?;
    writeln!(
        out,
        "        validator: Validator::{},",
        validator(rule.validator)
    )?;
    writeln!(out, "        secret_group: {},", rule.secret_group)?;
    writeln!(
        out,
        "        never_auto_delete: {},",
        rule.never_auto_delete
    )?;
    writeln!(out, "        anchor_only: {},", rule.anchor_only)?;
    match rule.entropy {
        Some(entropy) => writeln!(out, "        entropy: Some({entropy:?}),")?,
        None => writeln!(out, "        entropy: None,")?,
    }
    string_slice(out, "keywords", &rule.keywords, 2)?;
    writeln!(out, "        allowlists: &[")?;
    for allowlist in &rule.allowlists {
        render_allowlist(out, allowlist, 3, shared)?;
    }
    writeln!(out, "        ],")?;
    writeln!(out, "    }},")?;
    Ok(())
}

fn render_allowlist(
    out: &mut String,
    allowlist: &Allowlist,
    indent: usize,
    shared: &[Vec<String>],
) -> Result<()> {
    let pad = "    ".repeat(indent);
    writeln!(out, "{pad}AllowlistSpec {{")?;
    writeln!(
        out,
        "{pad}    condition: AllowlistCondition::{},",
        match allowlist.condition {
            Condition::Any => "Any",
            Condition::All => "All",
        }
    )?;
    writeln!(
        out,
        "{pad}    target: AllowlistTarget::{},",
        match allowlist.target {
            Target::Secret => "Secret",
            Target::Match => "Match",
            Target::Line => "Line",
        }
    )?;
    string_slice(out, "regexes", &allowlist.regexes, indent + 1)?;
    match shared
        .iter()
        .position(|words| *words == allowlist.stopwords)
    {
        Some(index) => writeln!(out, "{pad}    stopwords: {},", shared_name(index))?,
        None => string_slice(out, "stopwords", &allowlist.stopwords, indent + 1)?,
    }
    writeln!(
        out,
        "{pad}    stopword_minimum: {},",
        allowlist.stopword_minimum
    )?;
    writeln!(out, "{pad}}},")?;
    Ok(())
}

fn string_slice(out: &mut String, field: &str, values: &[String], indent: usize) -> Result<()> {
    let pad = "    ".repeat(indent);
    write!(out, "{pad}{field}: &[")?;
    if values.is_empty() {
        writeln!(out, "],")?;
        return Ok(());
    }
    writeln!(out)?;
    for value in values {
        writeln!(out, "{pad}    {},", rust_string(value))?;
    }
    writeln!(out, "{pad}],")?;
    Ok(())
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn category(value: Category) -> &'static str {
    match value {
        Category::Credential => "Credential",
        Category::Financial => "Financial",
        Category::PersonalId => "PersonalId",
        Category::Infrastructure => "Infrastructure",
    }
}

fn validator(value: Validator) -> &'static str {
    match value {
        Validator::None => "None",
        Validator::ValueStrength => "ValueStrength",
        Validator::CardNumber => "CardNumber",
        Validator::Iban => "Iban",
        Validator::SsnStructure => "SsnStructure",
        Validator::PhoneShape => "PhoneShape",
    }
}
