/**
 * CopyPaste v2 — design token build.
 *
 * `tokens/` is the only source of truth. This file is configuration for Style
 * Dictionary plus the platform formats Style Dictionary does not ship (a
 * Material 3 ColorScheme, a Tailwind v4 @theme layer). It does not parse,
 * resolve or transform tokens itself — that is the library's job.
 *
 * Run with `npm run build`. Everything it writes under `dist/` is generated;
 * see design/README.md.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import StyleDictionary from 'style-dictionary';

const EXT = 'com.copypaste';
const PACKAGE = 'app.copypaste.design';
const DIST = 'dist/';

/* ------------------------------------------------------------------ naming */

/**
 * How many leading path segments each top-level group contributes to nothing.
 * The remaining segments joined with `-` are the CSS custom property name, so
 * `color.raised-2` is `--raised-2` and `z.toast` is `--z-toast`. These names
 * are the vocabulary port-manifest §8 speaks, and keeping them means the v1
 * design reference stays readable as a visual oracle.
 */
const GROUP_DROP = {
  color: 1,
  elevation: 1,
  type: 1,
  space: 1,
  radius: 1,
  motion: 1,
  size: 1,
  layout: 1,
  z: 0,
  accents: 2, // accents.teal.accent -> accent (emitted under its own selector)
  translucency: 2, // translucency.frosted.chrome-bg -> chrome-bg
  tw: 1,
  m3: 1,
};

const varName = (token) => token.path.slice(GROUP_DROP[token.path[0]] ?? 0).join('-');

/**
 * Style Dictionary resolves references inside `$extensions` as well as inside
 * `$value`, so the *original* extensions are read here: `composeAlpha` has to
 * stay a reference in order to be emitted as a named Kotlin field rather than
 * as a magic number.
 */
const ext = (token) => token.original?.$extensions?.[EXT] ?? token.$extensions?.[EXT] ?? {};

const targets = (token) => ext(token).platforms ?? ['css', 'compose'];

const refPath = (token) => {
  const raw = token.original?.$value;
  if (typeof raw !== 'string') return null;
  const m = /^\{([^}]+)\}$/.exec(raw.trim());
  return m ? m[1].split('.') : null;
};

const camel = (name) =>
  name
    .split('-')
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');

const num = (value) => String(value).replace(/(px|em|ms|%)$/, '');

StyleDictionary.registerTransform({
  name: 'name/copypaste',
  type: 'name',
  transform: varName,
});

/* ----------------------------------------------------------------- filters */

const isThemed = (token) => /\.(dark|light)\.json$/.test(token.filePath);
const inGroup = (token, ...groups) => groups.includes(token.path[0]);

const banner = (what) => `/**
 * ${what}
 *
 * GENERATED by Style Dictionary from design/tokens/. DO NOT EDIT.
 * Change a token and run \`npm run build\` in design/.
 */
`;

const ktBanner = (what) => `/*
 * ${what}
 *
 * GENERATED by Style Dictionary from design/tokens/. DO NOT EDIT.
 * Change a token and run \`npm run build\` in design/.
 */
`;

/* ------------------------------------------------------------- CSS formats */

const decl = (token) => `  --${token.name}: ${token.$value ?? token.value};`;

/**
 * A themed block of custom properties, plus the two conditional blocks §8.5
 * and §8.6 attach to specific tokens: the prefers-reduced-motion override
 * (from a token's `reducedMotion` extension) and the translucency axis (from
 * the translucency group). Both live with the tokens rather than in a
 * stylesheet somebody has to remember to update.
 */
StyleDictionary.registerFormat({
  name: 'css/copypaste',
  format({ dictionary, options }) {
    const all = dictionary.allTokens;
    const frosted = all.filter((t) => t.path[0] === 'translucency' && t.path[1] === 'frosted');
    const solid = all.filter((t) => t.path[0] === 'translucency' && t.path[1] === 'solid');
    const main = all.filter((t) => t.path[0] !== 'translucency' || t.path[1] === 'solid');
    const reduced = all.filter((t) => ext(t).reducedMotion !== undefined);

    const out = [banner(options.title)];
    const selectors = options.selectors.join(',\n');
    const indent = (block, pad) => block.replace(/^/gm, pad);

    out.push(`${selectors} {`);
    if (options.prelude) out.push(`  ${options.prelude}`);
    out.push(main.map(decl).join('\n'), '}\n');

    if (reduced.length) {
      out.push(
        '/* §8.5: all three durations collapse to 0ms under reduced motion. */',
        '@media (prefers-reduced-motion: reduce) {',
        indent(`${selectors} {`, '  '),
        reduced.map((t) => `    --${t.name}: ${ext(t).reducedMotion};`).join('\n'),
        '  }',
        '}\n',
      );
    }

    if (frosted.length) {
      const on = options.selectors.map((s) => `${s}[data-translucency="on"]`).join(',\n');
      out.push(
        '/* §8.6: solid is the baseline. Frosting is additive inside @supports, so an',
        ' * engine without backdrop-filter gets the solid fallback with no separate',
        ' * rule and no lower-specificity rule for the on-state to defeat. */',
        '@supports (backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px)) {',
        indent(`${on} {`, '  '),
        frosted.map((t) => `    --${t.name}: ${t.$value ?? t.value};`).join('\n'),
        '  }\n',
        '  /* Authored last at the same specificity, so it wins wherever it matches. */',
        '  @media (prefers-reduced-transparency: reduce) {',
        indent(`${on} {`, '    '),
        solid.map((t) => `      --${t.name}: ${t.$value ?? t.value};`).join('\n'),
        '    }',
        '  }',
        '}\n',
      );
    }

    return out.join('\n');
  },
});

/** One block per accent, on the [data-accent] axis (§8.4). */
StyleDictionary.registerFormat({
  name: 'css/copypaste-accents',
  format({ dictionary, options }) {
    const byAccent = new Map();
    for (const token of dictionary.allTokens) {
      const accent = token.path[1];
      if (!byAccent.has(accent)) byAccent.set(accent, []);
      byAccent.get(accent).push(token);
    }
    const blocks = [...byAccent].map(([accent, tokens]) => {
      const selectors = options.selectors.map((s) => s.replace('%s', accent)).join(',\n');
      return `${selectors} {\n${tokens.map(decl).join('\n')}\n}`;
    });
    return [banner(options.title), blocks.join('\n\n'), ''].join('\n');
  },
});

/**
 * The Tailwind v4 theme layer. Two parts:
 *   1. the explicit semantic slots from tokens/semantic/tailwind.json — the
 *      shadcn/ui contract, and the half of the mapping table the desktop uses;
 *   2. a mechanical bridge exposing every core token as a Tailwind theme key,
 *      so `bg-panel`, `text-c-url`, `rounded-card` and `shadow-2` exist without
 *      anybody maintaining a list.
 * Explicit slots win — that is how `--color-accent` stays shadcn's neutral
 * hover surface rather than our brand colour, which is `--color-primary`.
 */
StyleDictionary.registerFormat({
  name: 'css/copypaste-tailwind',
  format({ dictionary, options }) {
    const byPath = new Map(dictionary.allTokens.map((t) => [t.path.join('.'), t]));
    const lines = new Map();

    const alias = (key, token, why) => {
      const ref = refPath(token);
      if (!ref) throw new Error(`tw.${token.path[1]} must be a pure alias, got ${token.original.$value}`);
      const target = byPath.get(ref.join('.'));
      if (!target) throw new Error(`tw.${token.path[1]} references unknown token {${ref.join('.')}}`);
      lines.set(key, `  --${key}: var(--${varName(target)});${why ? ` /* ${why} */` : ''}`);
    };

    for (const token of dictionary.allTokens.filter((t) => t.path[0] === 'tw')) {
      alias(varName(token), token);
    }

    const bridge = (key, token) => {
      if (lines.has(key)) return; // an explicit semantic slot already claimed it
      lines.set(key, `  --${key}: var(--${varName(token)});`);
    };
    for (const token of dictionary.allTokens) {
      const name = varName(token);
      switch (token.path[0]) {
        case 'color':
          if (token.$type === 'color') bridge(`color-${name}`, token);
          break;
        case 'accents':
          break;
        case 'elevation':
          bridge(`shadow-${name.replace(/^sh-?/, '')}`, token);
          break;
        case 'radius':
          bridge(`radius-${name.replace(/^r-/, '')}`, token);
          break;
        case 'space':
          if (token.$type === 'dimension') bridge(`spacing-${name}`, token);
          break;
        case 'type':
          if (name.startsWith('fs-')) bridge(`text-${name}`, token);
          break;
        default:
          break;
      }
    }

    return `${banner(options.title)}
/* Tailwind v4 reads its theme from CSS custom properties. \`inline\` means the
 * utilities emit var(--our-token) rather than a copy of the value, so switching
 * [data-theme] or [data-accent] re-tints every shadcn component with no
 * per-component override and no second palette. */
@theme inline {
${[...lines.values()].join('\n')}
}
`;
  },
});

StyleDictionary.registerFormat({
  name: 'css/copypaste-index',
  format({ options }) {
    return `${banner(options.title)}
/* Import order is the cascade. Base first, then the two themes, then the accent
 * axis (which must beat the theme blocks it shares specificity with), then the
 * Tailwind layer. Import \`tailwindcss\` before this file. */
${options.imports.map((f) => `@import "./${f}";`).join('\n')}
`;
  },
});

/* --------------------------------------------------- Compose (Kotlin) output
 * A Compose ColorScheme needs both themes in one file, so the build collects
 * each theme's transformed tokens up front and these formats read from that.
 */

const compose = { dark: null, light: null };

const colorTokens = (theme) =>
  compose[theme].allTokens.filter(
    (t) => inGroup(t, 'color') && t.$type === 'color' && targets(t).includes('compose'),
  );
const numberTokens = (theme) =>
  compose[theme].allTokens.filter((t) => inGroup(t, 'color') && t.$type === 'number');
const accentTokens = (theme) => compose[theme].allTokens.filter((t) => inGroup(t, 'accents'));

const kt = (token) => `${camel(varName(token))}`;

StyleDictionary.registerFormat({
  name: 'compose/copypaste-colors',
  format({ options }) {
    const fields = [
      ...colorTokens('dark').map((t) => ({ name: kt(t), type: 'Color', doc: t.$description })),
      ...numberTokens('dark').map((t) => ({ name: kt(t), type: 'Float', doc: t.$description })),
    ];
    const values = (theme) => {
      const byName = new Map(
        [...colorTokens(theme), ...numberTokens(theme)].map((t) => [kt(t), t]),
      );
      return fields
        .map((f) => {
          const t = byName.get(f.name);
          if (!t) throw new Error(`token ${f.name} missing from the ${theme} theme`);
          return `  ${f.name} = ${f.type === 'Float' ? `${t.$value}f` : t.$value},`;
        })
        .join('\n');
    };
    const accents = (theme) =>
      [...new Set(accentTokens(theme).map((t) => t.path[1]))]
        .map((accent) => {
          const of = (leaf) =>
            accentTokens(theme).find((t) => t.path[1] === accent && t.path[2] === leaf).$value;
          const name = accent.charAt(0).toUpperCase() + accent.slice(1);
          return `  CopyPasteAccent.${name} to CopyPasteAccentColors(${of('accent')}, ${of('accent-2')}, ${of('on-accent')}),`;
        })
        .join('\n');

    return `${ktBanner(options.title)}
package ${PACKAGE}

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/** Every theme-varying CopyPaste colour, in one shape so both themes are interchangeable. */
@Immutable
public data class CopyPasteColors(
${fields.map((f) => `  /** ${(f.doc ?? '').replace(/\*\//g, '')} */\n  public val ${f.name}: ${f.type},`).join('\n')}
)

public val copyPasteDarkColors: CopyPasteColors = CopyPasteColors(
${values('dark')}
)

public val copyPasteLightColors: CopyPasteColors = CopyPasteColors(
${values('light')}
)

/** The accent axis (§8.4). User-selectable; the same six the desktop offers. */
public enum class CopyPasteAccent { Indigo, Blue, Teal, Green, Amber, Rose }

@Immutable
public data class CopyPasteAccentColors(
  public val accent: Color,
  public val accent2: Color,
  public val onAccent: Color,
)

public val copyPasteDarkAccents: Map<CopyPasteAccent, CopyPasteAccentColors> = mapOf(
${accents('dark')}
)

public val copyPasteLightAccents: Map<CopyPasteAccent, CopyPasteAccentColors> = mapOf(
${accents('light')}
)
`;
  },
});

StyleDictionary.registerFormat({
  name: 'compose/copypaste-colorscheme',
  format({ options }) {
    const ACCENT_FIELD = { accent: 'a.accent', 'accent-2': 'a.accent2', 'on-accent': 'a.onAccent' };

    const slots = compose.dark.allTokens.filter((t) => inGroup(t, 'm3'));
    const args = slots
      .map((token) => {
        const slot = token.path[1];
        const ref = refPath(token);
        if (!ref || ref[0] !== 'color') {
          throw new Error(`m3.${slot} must be a pure {color.*} alias, got ${token.original.$value}`);
        }
        const base = ACCENT_FIELD[ref[1]] ?? `c.${camel(ref[1])}`;
        const alphaRef = ext(token).composeAlpha;
        if (!alphaRef) return `    ${slot} = ${base},`;
        const alpha = /^\{color\.([^}]+)\}$/.exec(alphaRef);
        if (!alpha) throw new Error(`m3.${slot} composeAlpha must reference a {color.*} number`);
        return `    ${slot} = ${base}.copy(alpha = c.${camel(alpha[1])}),`;
      })
      .join('\n');

    const scheme = (theme) => `/**
 * The CopyPaste ${theme} theme as a Material 3 ColorScheme. Every stock Material
 * component is themed by this — see the mapping table in design/README.md for
 * which CopyPaste token feeds each role.
 */
public fun copyPaste${theme.charAt(0).toUpperCase() + theme.slice(1)}ColorScheme(
  accent: CopyPasteAccent = CopyPasteAccent.Indigo,
): ColorScheme {
  val c = copyPaste${theme.charAt(0).toUpperCase() + theme.slice(1)}Colors
  val a = copyPaste${theme.charAt(0).toUpperCase() + theme.slice(1)}Accents.getValue(accent)
  return ${theme}ColorScheme(
${args}
  )
}`;

    return `${ktBanner(options.title)}
package ${PACKAGE}

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.staticCompositionLocalOf

${scheme('dark')}

${scheme('light')}

/**
 * The CopyPaste tokens Material 3 has no role for — the content-kind hues
 * (§8.7), the AA-corrected *Strong text variants (§8.3) and the state layers.
 * Provide it alongside MaterialTheme; read it for anything the ColorScheme
 * cannot express.
 */
public val LocalCopyPasteColors: androidx.compose.runtime.ProvidableCompositionLocal<CopyPasteColors> =
  staticCompositionLocalOf { copyPasteDarkColors }
`;
  },
});

StyleDictionary.registerFormat({
  name: 'compose/copypaste-dimens',
  format({ options }) {
    const all = compose.dark.allTokens;
    const pick = (group, predicate = () => true) =>
      all.filter((t) => inGroup(t, group) && targets(t).includes('compose') && predicate(t));

    const object = (name, doc, tokens, render) =>
      tokens.length === 0
        ? ''
        : `/** ${doc} */\npublic object ${name} {\n${tokens
            .map((t) => `${t.$description ? `  /** ${t.$description.replace(/\*\//g, '')} */\n` : ''}  public val ${camel(varName(t))}: ${render(t).type} = ${render(t).value}`)
            .join('\n')}\n}\n`;

    const dp = (t) => ({ type: 'Dp', value: `${num(t.$value)}.dp` });
    const sp = (t) => ({ type: 'TextUnit', value: `${num(t.$value)}.sp` });
    const em = (t) => ({ type: 'TextUnit', value: `${Number(num(t.$value)) < 0 ? `(${num(t.$value)}f)` : `${num(t.$value)}f`}.em` });

    const type = pick('type');
    return `${ktBanner(options.title)}
package ${PACKAGE}

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.animation.core.Easing
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

${object('CopyPasteSpacing', 'Spacing scale, gaps and padding (§8.5). Not a 4pt grid — the odd steps are deliberate.', pick('space', (t) => t.$type === 'dimension'), dp)}
${object('CopyPasteRadius', 'Corner radii (§8.5).', pick('radius'), dp)}
${object('CopyPasteSize', 'Fixed control, icon and stroke sizes (§8.5).', pick('size'), dp)}
${object('CopyPasteLayout', 'Container geometry (§8.5). Android reads these as max content widths.', pick('layout'), dp)}
${object('CopyPasteFontSize', 'Type ladder (§8.5). The half-point steps are load-bearing at list density.', type.filter((t) => varName(t).startsWith('fs-')), sp)}
${object('CopyPasteFontWeight', 'Weight ladder (§8.5). Body is 450, not 400.', type.filter((t) => t.$type === 'fontWeight'), (t) => ({ type: 'FontWeight', value: `FontWeight(${t.$value})` }))}
${object('CopyPasteLineHeight', 'Line-height multipliers (§8.5).', type.filter((t) => varName(t).startsWith('lh-')), (t) => ({ type: 'Float', value: `${t.$value}f` }))}
${object('CopyPasteLetterSpacing', 'Tracking (§8.5).', type.filter((t) => varName(t).startsWith('ls-')), em)}
${object('CopyPasteDuration', 'Transition durations in milliseconds (§8.5). Collapse these to 0 when the system reports reduced motion.', pick('motion', (t) => t.$type === 'duration'), (t) => ({ type: 'Int', value: num(t.$value) }))}
${object('CopyPasteZ', 'Stacking order (§8.5).', pick('z'), (t) => ({ type: 'Float', value: `${t.$value}f` }))}
/** The single CopyPaste easing curve (§8.5). Everything uses it. */
public val CopyPasteEase: Easing = CubicBezierEasing(${compose.dark.allTokens
      .find((t) => varName(t) === 'ease')
      .original.$value.map((n) => `${n}f`)
      .join(', ')})
`;
  },
});

/* ----------------------------------------------------------- platform setup */

const sources = (theme) => [
  `tokens/color/theme.${theme}.json`,
  `tokens/color/accents.${theme}.json`,
  `tokens/color/static.json`,
  `tokens/elevation.${theme}.json`,
  'tokens/elevation.static.json',
  'tokens/typography.json',
  'tokens/spacing.json',
  'tokens/radius.json',
  'tokens/motion.json',
  'tokens/size.json',
  'tokens/layout.json',
  'tokens/z-index.json',
  'tokens/translucency.json',
  'tokens/semantic/tailwind.json',
  'tokens/semantic/material.json',
];

const CSS_TRANSFORMS = [
  'name/copypaste',
  'shadow/css/shorthand',
  'fontFamily/css',
  'cubicBezier/css',
];

/**
 * No colour transform on the CSS side on purpose: the token values are already
 * exactly the CSS §8 specifies, including the rgba() state layers and the
 * color-mix() selection fill, and round-tripping them through a colour parser
 * would only introduce drift.
 */
const cssPlatform = (theme, files) => ({
  transforms: CSS_TRANSFORMS,
  buildPath: DIST,
  files,
});

const composePlatform = (files) => ({
  transforms: ['name/copypaste', 'color/composeColor'],
  buildPath: DIST,
  files,
});

const themeConfig = (theme) => ({
  source: sources(theme),
  log: { verbosity: 'silent', warnings: 'warn' },
  platforms: {
    css: cssPlatform(theme, cssFiles(theme)),
    compose: composePlatform(theme === 'dark' ? composeFiles() : []),
    ...(theme === 'dark' ? { tailwind: cssPlatform(theme, [tailwindFile()]) } : {}),
  },
});

const themeSelectors = (theme) =>
  theme === 'dark'
    ? [':root', ':root[data-theme="dark"]', '.theme-scope[data-theme="dark"]']
    : [':root[data-theme="light"]', '.theme-scope[data-theme="light"]'];

const accentSelectors = (theme) =>
  theme === 'dark'
    ? [':root[data-accent="%s"]', '.theme-scope[data-accent="%s"]']
    : [
        ':root[data-theme="light"][data-accent="%s"]',
        '.theme-scope[data-theme="light"][data-accent="%s"]',
      ];

function cssFiles(theme) {
  const files = [
    {
      destination: `css/tokens.${theme}.css`,
      format: 'css/copypaste',
      filter: (t) => isThemed(t) && inGroup(t, 'color', 'elevation') && targets(t).includes('css'),
      options: {
        title: `CopyPaste ${theme} theme — port-manifest §8.${theme === 'dark' ? 1 : 2}, §8.3.`,
        selectors: themeSelectors(theme),
        prelude: `color-scheme: ${theme};`,
      },
    },
    {
      destination: `css/accents.${theme}.css`,
      format: 'css/copypaste-accents',
      filter: (t) => inGroup(t, 'accents'),
      options: {
        title: `CopyPaste accent axis, ${theme} — port-manifest §8.4.`,
        selectors: accentSelectors(theme),
      },
    },
  ];
  if (theme !== 'dark') return files;
  return [
    {
      destination: 'css/tokens.base.css',
      format: 'css/copypaste',
      filter: (t) =>
        !isThemed(t) && !inGroup(t, 'tw', 'm3', 'accents') && targets(t).includes('css'),
      options: {
        title: 'CopyPaste theme-independent tokens — port-manifest §8.5, §8.6.',
        selectors: [':root'],
      },
    },
    ...files,
    {
      destination: 'css/index.css',
      format: 'css/copypaste-index',
      // The format emits imports, not tokens; the filter only has to be non-empty
      // so Style Dictionary writes the file.
      filter: (t) => inGroup(t, 'z'),
      options: {
        title: 'CopyPaste design tokens — entry point.',
        imports: [
          'tokens.base.css',
          'tokens.dark.css',
          'tokens.light.css',
          'accents.dark.css',
          'accents.light.css',
          'theme.css',
        ],
      },
    },
  ];
}

const tailwindFile = () => ({
  destination: 'css/theme.css',
  format: 'css/copypaste-tailwind',
  filter: (t) => !inGroup(t, 'm3'),
  options: { title: 'CopyPaste Tailwind v4 theme layer — the shadcn/ui semantic contract.' },
});

const composeFiles = () => [
  {
    destination: 'compose/Color.kt',
    format: 'compose/copypaste-colors',
    filter: (t) => inGroup(t, 'color', 'accents'),
    options: { title: 'CopyPaste colours for Jetpack Compose.' },
  },
  {
    destination: 'compose/ColorScheme.kt',
    format: 'compose/copypaste-colorscheme',
    filter: (t) => inGroup(t, 'm3'),
    options: { title: 'CopyPaste Material 3 ColorSchemes.' },
  },
  {
    destination: 'compose/Dimens.kt',
    format: 'compose/copypaste-dimens',
    filter: (t) => inGroup(t, 'space', 'radius', 'size', 'layout', 'type', 'motion', 'z'),
    options: { title: 'CopyPaste spacing, radii, sizes, type and motion for Compose.' },
  },
];

/* ------------------------------------------------------------------- build */

const dark = new StyleDictionary(themeConfig('dark'));
const light = new StyleDictionary(themeConfig('light'));
await Promise.all([dark.hasInitialized, light.hasInitialized]);

compose.dark = await dark.getPlatformTokens('compose');
compose.light = await light.getPlatformTokens('compose');

await dark.buildAllPlatforms();
await light.buildPlatform('css');

await mkdir(`${DIST}compose`, { recursive: true });
await writeFile(
  `${DIST}README.txt`,
  'Everything in this directory is generated from design/tokens/ by Style Dictionary.\n' +
    'Do not edit it. Run `npm run build` in design/ instead.\n',
);

console.log(
  `built ${compose.dark.allTokens.length} dark and ` +
    `${compose.light.allTokens.length} light resolved tokens -> ${DIST}`,
);
