/**
 * CopyPaste v2 — design token build.
 *
 * `tokens/` is the only source of truth. This file is configuration for Style
 * Dictionary plus the one platform format Style Dictionary does not ship (a
 * Tailwind v4 `@theme` layer). It does not parse, resolve or transform tokens
 * itself — that is the library's job.
 *
 * Run with `npm run build`. Everything it writes under `dist/` is generated;
 * see design/README.md.
 */

import { writeFile } from 'node:fs/promises';
import StyleDictionary from 'style-dictionary';

const EXT = 'com.copypaste';
const DIST = 'dist/';

/* ------------------------------------------------------------------ naming */

/**
 * How many leading path segments each top-level group contributes to nothing.
 * The remaining segments joined with `-` are the CSS custom property name, so
 * `color.raised-2` is `--raised-2` and `z.toast` is `--z-toast`. The names are
 * unchanged from v1 even though every value has changed, so port-manifest §8
 * still reads as a map of what exists — only its values are now reference.
 */
const GROUP_DROP = {
  color: 1,
  elevation: 1,
  type: 1,
  space: 1,
  radius: 1,
  motion: 1,
  size: 1,
  layout: 1,
  z: 0,
  accents: 2, // accents.teal.accent -> accent (emitted under its own selector)
  translucency: 2, // translucency.frosted.chrome-bg -> chrome-bg
  tw: 1,
};

const varName = (token) => token.path.slice(GROUP_DROP[token.path[0]] ?? 0).join('-');

/**
 * Style Dictionary resolves references inside `$extensions` as well as inside
 * `$value`, so the *original* extensions are read here — a token's own
 * `reducedMotion` or `platforms` entry must survive reference resolution.
 */
const ext = (token) => token.original?.$extensions?.[EXT] ?? token.$extensions?.[EXT] ?? {};

const targets = (token) => ext(token).platforms ?? ['css'];

const refPath = (token) => {
  const raw = token.original?.$value;
  if (typeof raw !== 'string') return null;
  const m = /^\{([^}]+)\}$/.exec(raw.trim());
  return m ? m[1].split('.') : null;
};

StyleDictionary.registerTransform({
  name: 'name/copypaste',
  type: 'name',
  transform: varName,
});

/* ----------------------------------------------------------------- filters */

const isThemed = (token) => /\.(dark|light)\.json$/.test(token.filePath);
const inGroup = (token, ...groups) => groups.includes(token.path[0]);

const banner = (what) => `/**
 * ${what}
 *
 * GENERATED by Style Dictionary from design/tokens/. DO NOT EDIT.
 * Change a token and run \`npm run build\` in design/.
 */
`;

/* ------------------------------------------------------------- CSS formats */

const decl = (token) => `  --${token.name}: ${token.$value ?? token.value};`;

/**
 * A themed block of custom properties, plus the conditional blocks that attach
 * to specific tokens: the prefers-reduced-motion override, the pointer:coarse
 * override, and the translucency axis. Each lives with its tokens rather than
 * in a stylesheet somebody has to remember to update.
 */
StyleDictionary.registerFormat({
  name: 'css/copypaste',
  format({ dictionary, options }) {
    const all = dictionary.allTokens;
    const frosted = all.filter((t) => t.path[0] === 'translucency' && t.path[1] === 'frosted');
    const solid = all.filter((t) => t.path[0] === 'translucency' && t.path[1] === 'solid');
    const main = all.filter((t) => t.path[0] !== 'translucency' || t.path[1] === 'solid');
    const reduced = all.filter((t) => ext(t).reducedMotion !== undefined);
    const coarse = all.filter((t) => ext(t).coarsePointer !== undefined);

    const out = [banner(options.title)];
    const selectors = options.selectors.join(',\n');
    const indent = (block, pad) => block.replace(/^/gm, pad);

    out.push(`${selectors} {`);
    if (options.prelude) out.push(`  ${options.prelude}`);
    out.push(main.map(decl).join('\n'), '}\n');

    if (reduced.length) {
      out.push(
        '/* §8.5: all three durations collapse to 0ms under reduced motion. */',
        '@media (prefers-reduced-motion: reduce) {',
        indent(`${selectors} {`, '  '),
        reduced.map((t) => `    --${t.name}: ${ext(t).reducedMotion};`).join('\n'),
        '  }',
        '}\n',
      );
    }

    if (coarse.length) {
      out.push(
        '/* Touch targets. `pointer: coarse` is the primary pointer being a finger,',
        ' * which is the Android build and a Mac in tablet-mirroring — not a screen',
        ' * width, because a narrow window on a Mac is still driven by a mouse. */',
        '@media (pointer: coarse) {',
        indent(`${selectors} {`, '  '),
        coarse.map((t) => `    --${t.name}: ${ext(t).coarsePointer};`).join('\n'),
        '  }',
        '}\n',
      );
    }

    if (frosted.length) {
      const on = options.selectors.map((s) => `${s}[data-translucency="on"]`).join(',\n');
      out.push(
        '/* §8.6: solid is the baseline. Frosting is additive inside @supports, so an',
        ' * engine without backdrop-filter gets the solid fallback with no separate',
        ' * rule and no lower-specificity rule for the on-state to defeat. */',
        '@supports (backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px)) {',
        indent(`${on} {`, '  '),
        frosted.map((t) => `    --${t.name}: ${t.$value ?? t.value};`).join('\n'),
        '  }\n',
        '  /* Authored last at the same specificity, so it wins wherever it matches. */',
        '  @media (prefers-reduced-transparency: reduce) {',
        indent(`${on} {`, '    '),
        solid.map((t) => `      --${t.name}: ${t.$value ?? t.value};`).join('\n'),
        '    }',
        '  }',
        '}\n',
      );
    }

    return out.join('\n');
  },
});

/** One block per accent, on the [data-accent] axis (§8.4). */
StyleDictionary.registerFormat({
  name: 'css/copypaste-accents',
  format({ dictionary, options }) {
    const byAccent = new Map();
    for (const token of dictionary.allTokens) {
      const accent = token.path[1];
      if (!byAccent.has(accent)) byAccent.set(accent, []);
      byAccent.get(accent).push(token);
    }
    const blocks = [...byAccent].map(([accent, tokens]) => {
      const selectors = options.selectors.map((s) => s.replace('%s', accent)).join(',\n');
      return `${selectors} {\n${tokens.map(decl).join('\n')}\n}`;
    });
    return [banner(options.title), blocks.join('\n\n'), ''].join('\n');
  },
});

/**
 * The Tailwind v4 theme layer. Two parts:
 *   1. the explicit semantic slots from tokens/semantic/tailwind.json — the
 *      shadcn/ui contract, and the half of the mapping table the desktop uses;
 *   2. a mechanical bridge exposing every core token as a Tailwind theme key,
 *      so `bg-panel`, `text-c-url`, `rounded-card` and `shadow-2` exist without
 *      anybody maintaining a list.
 * Explicit slots win — that is how `--color-accent` stays shadcn's neutral
 * hover surface rather than our brand colour, which is `--color-primary`.
 */
StyleDictionary.registerFormat({
  name: 'css/copypaste-tailwind',
  format({ dictionary, options }) {
    const byPath = new Map(dictionary.allTokens.map((t) => [t.path.join('.'), t]));
    const lines = new Map();

    const alias = (key, token, why) => {
      const ref = refPath(token);
      if (!ref) throw new Error(`tw.${token.path[1]} must be a pure alias, got ${token.original.$value}`);
      const target = byPath.get(ref.join('.'));
      if (!target) throw new Error(`tw.${token.path[1]} references unknown token {${ref.join('.')}}`);
      lines.set(key, `  --${key}: var(--${varName(target)});${why ? ` /* ${why} */` : ''}`);
    };

    for (const token of dictionary.allTokens.filter((t) => t.path[0] === 'tw')) {
      alias(varName(token), token);
    }

    const bridge = (key, token) => {
      if (lines.has(key)) return; // an explicit semantic slot already claimed it
      lines.set(key, `  --${key}: var(--${varName(token)});`);
    };
    for (const token of dictionary.allTokens) {
      const name = varName(token);
      switch (token.path[0]) {
        case 'color':
          if (token.$type === 'color') bridge(`color-${name}`, token);
          break;
        case 'accents':
          break;
        case 'elevation':
          bridge(`shadow-${name.replace(/^sh-?/, '')}`, token);
          break;
        case 'radius':
          bridge(`radius-${name.replace(/^r-/, '')}`, token);
          break;
        case 'space':
          if (token.$type === 'dimension') bridge(`spacing-${name}`, token);
          break;
        case 'type':
          if (name.startsWith('fs-')) bridge(`text-${name}`, token);
          break;
        default:
          break;
      }
    }

    return `${banner(options.title)}
/* Tailwind v4 reads its theme from CSS custom properties. \`inline\` means the
 * utilities emit var(--our-token) rather than a copy of the value, so switching
 * [data-theme] or [data-accent] re-tints every shadcn component with no
 * per-component override and no second palette. */
@theme inline {
${[...lines.values()].join('\n')}
}
`;
  },
});

StyleDictionary.registerFormat({
  name: 'css/copypaste-index',
  format({ options }) {
    return `${banner(options.title)}
/* Import order is the cascade. Base first, then the two themes, then the accent
 * axis (which must beat the theme blocks it shares specificity with), then the
 * Tailwind layer. Import \`tailwindcss\` before this file. */
${options.imports.map((f) => `@import "./${f}";`).join('\n')}
`;
  },
});

/* ----------------------------------------------------------- platform setup */

const sources = (theme) => [
  `tokens/color/theme.${theme}.json`,
  `tokens/color/accents.${theme}.json`,
  `tokens/color/static.json`,
  `tokens/elevation.${theme}.json`,
  'tokens/elevation.static.json',
  'tokens/typography.json',
  'tokens/spacing.json',
  'tokens/radius.json',
  'tokens/motion.json',
  'tokens/size.json',
  'tokens/layout.json',
  'tokens/z-index.json',
  'tokens/translucency.json',
  'tokens/semantic/tailwind.json',
];

const CSS_TRANSFORMS = [
  'name/copypaste',
  'shadow/css/shorthand',
  'fontFamily/css',
  'cubicBezier/css',
];

/**
 * No colour transform on the CSS side on purpose: the token values are already
 * exactly the CSS §8 specifies, including the rgba() state layers and the
 * color-mix() selection fill, and round-tripping them through a colour parser
 * would only introduce drift.
 */
const cssPlatform = (theme, files) => ({
  transforms: CSS_TRANSFORMS,
  buildPath: DIST,
  files,
});

const themeConfig = (theme) => ({
  source: sources(theme),
  log: { verbosity: 'silent', warnings: 'warn' },
  platforms: {
    css: cssPlatform(theme, cssFiles(theme)),
    ...(theme === 'dark' ? { tailwind: cssPlatform(theme, [tailwindFile()]) } : {}),
  },
});

const themeSelectors = (theme) =>
  theme === 'dark'
    ? [':root', ':root[data-theme="dark"]', '.theme-scope[data-theme="dark"]']
    : [':root[data-theme="light"]', '.theme-scope[data-theme="light"]'];

const accentSelectors = (theme) =>
  theme === 'dark'
    ? [':root[data-accent="%s"]', '.theme-scope[data-accent="%s"]']
    : [
        ':root[data-theme="light"][data-accent="%s"]',
        '.theme-scope[data-theme="light"][data-accent="%s"]',
      ];

function cssFiles(theme) {
  const files = [
    {
      destination: `css/tokens.${theme}.css`,
      format: 'css/copypaste',
      filter: (t) => isThemed(t) && inGroup(t, 'color', 'elevation') && targets(t).includes('css'),
      options: {
        title: `CopyPaste ${theme} theme — shadcn/ui default theme, zinc base (OKLCH).`,
        selectors: themeSelectors(theme),
        prelude: `color-scheme: ${theme};`,
      },
    },
    {
      destination: `css/accents.${theme}.css`,
      format: 'css/copypaste-accents',
      filter: (t) => inGroup(t, 'accents'),
      options: {
        title: `CopyPaste accent axis, ${theme} — Tailwind v4 palette steps.`,
        selectors: accentSelectors(theme),
      },
    },
  ];
  if (theme !== 'dark') return files;
  return [
    {
      destination: 'css/tokens.base.css',
      format: 'css/copypaste',
      filter: (t) =>
        !isThemed(t) && !inGroup(t, 'tw', 'accents') && targets(t).includes('css'),
      options: {
        title: 'CopyPaste theme-independent tokens — type, space, radius, motion, size.',
        selectors: [':root'],
      },
    },
    ...files,
    {
      destination: 'css/index.css',
      format: 'css/copypaste-index',
      // The format emits imports, not tokens; the filter only has to be non-empty
      // so Style Dictionary writes the file.
      filter: (t) => inGroup(t, 'z'),
      options: {
        title: 'CopyPaste design tokens — entry point.',
        imports: [
          'tokens.base.css',
          'tokens.dark.css',
          'tokens.light.css',
          'accents.dark.css',
          'accents.light.css',
          'theme.css',
        ],
      },
    },
  ];
}

const tailwindFile = () => ({
  destination: 'css/theme.css',
  format: 'css/copypaste-tailwind',
  options: { title: 'CopyPaste Tailwind v4 theme layer — the shadcn/ui semantic contract.' },
});

/* ------------------------------------------------------------------- build */

const dark = new StyleDictionary(themeConfig('dark'));
const light = new StyleDictionary(themeConfig('light'));
await Promise.all([dark.hasInitialized, light.hasInitialized]);

await dark.buildAllPlatforms();
await light.buildPlatform('css');

await writeFile(
  `${DIST}README.txt`,
  'Everything in this directory is generated from design/tokens/ by Style Dictionary.\n' +
    'Do not edit it. Run `npm run build` in design/ instead.\n',
);

const [darkTokens, lightTokens] = await Promise.all([
  dark.getPlatformTokens('css'),
  light.getPlatformTokens('css'),
]);

console.log(
  `built ${darkTokens.allTokens.length} dark and ` +
    `${lightTokens.allTokens.length} light resolved tokens -> ${DIST}`,
);
