/**
 * CopyPaste v2 — design token build.
 *
 * `tokens/` is the only source of truth. This file is configuration for Style
 * Dictionary plus the custom CSS formats Style Dictionary does not ship.
 * Style Dictionary owns token references and transforms; Culori owns the
 * recipe colour maths used for legacy-WebView fallbacks.
 *
 * Run with `npm run build`. Everything it writes under `dist/` is generated;
 * see design/README.md.
 */

import { writeFile } from 'node:fs/promises';
import { formatRgb } from 'culori';
import StyleDictionary from 'style-dictionary';
import { resolve } from './lib/tokens.mjs';

const EXT = 'com.copypaste';
const DIST = 'dist/';

/* ------------------------------------------------------------------ naming */

/**
 * How many leading path segments each top-level group contributes to nothing.
 * The remaining segments joined with `-` are the CSS custom property name, so
 * `color.raised-2` is `--raised-2` and `z.toast` is `--z-toast`. Stable names
 * keep generated CSS and component consumers on one contract.
 */
const GROUP_DROP = {
  color: 1,
  recipe: 2, // recipe.theme.control-focus-border -> control-focus-border
  elevation: 1,
  type: 1,
  space: 1,
  radius: 1,
  motion: 1,
  size: 1,
  layout: 1,
  media: 1,
  z: 0,
  themes: 2, // themes.aurora.accent -> accent (emitted under its own selector)
  translucency: 2, // translucency.frosted.chrome-bg -> chrome-bg
  tw: 1,
};

const varName = (token) => token.path.slice(GROUP_DROP[token.path[0]] ?? 0).join('-');

/**
 * Style Dictionary resolves references inside `$extensions` as well as inside
 * `$value`, so the *original* extensions are read here — a token's own
 * `reducedMotion` or `platforms` entry must survive reference resolution.
 */
const ext = (token) => token.original?.$extensions?.[EXT] ?? token.$extensions?.[EXT] ?? {};

const targets = (token) => ext(token).platforms ?? ['css'];

const refPath = (token) => {
  const raw = token.original?.$value;
  if (typeof raw !== 'string') return null;
  const m = /^\{([^}]+)\}$/.exec(raw.trim());
  return m ? m[1].split('.') : null;
};

StyleDictionary.registerTransform({
  name: 'name/copypaste',
  type: 'name',
  transform: varName,
});

/* ----------------------------------------------------------------- filters */

const isThemed = (token) => /\.(dark|light)\.json$/.test(token.filePath);
const inGroup = (token, ...groups) => groups.includes(token.path[0]);

const banner = (what) => `/**
 * ${what}
 *
 * GENERATED by Style Dictionary from design/tokens/. DO NOT EDIT.
 * Change a token and run \`npm run build\` in design/.
 */
`;

/* ------------------------------------------------------------- CSS formats */

const tokenValue = (token) => token.$value ?? token.value;

const recipeVars = (tokens) =>
  Object.fromEntries(tokens.map((token) => [token.name, tokenValue(token)]));

/** Recipes stay expressive in tokens/, but shipping CSS is concrete. Culori is
 *  already the design package's colour engine, so fallback generation and the
 *  contrast gate use the same OKLab interpolation and alpha semantics. */
function decl(token, vars) {
  const value = tokenValue(token);
  if (token.path[0] !== 'recipe') return `  --${token.name}: ${value};`;
  try {
    return `  --${token.name}: ${formatRgb(resolve(value, vars))};`;
  } catch (error) {
    throw new Error(`cannot resolve ${token.path.join('.')} from ${token.filePath}: ${error.message}`);
  }
}

const declarations = (tokens, context = tokens) => {
  const vars = recipeVars(context);
  return tokens.map((token) => decl(token, vars)).join('\n');
};

/**
 * A themed block of custom properties, plus the conditional blocks that attach
 * to specific tokens: the prefers-reduced-motion override, the pointer:coarse
 * override, and the translucency axis. Each lives with its tokens rather than
 * in a stylesheet somebody has to remember to update.
 */
StyleDictionary.registerFormat({
  name: 'css/copypaste',
  format({ dictionary, options }) {
    const all = dictionary.allTokens;
    const frosted = all.filter((t) => t.path[0] === 'translucency' && t.path[1] === 'frosted');
    const solid = all.filter((t) => t.path[0] === 'translucency' && t.path[1] === 'solid');
    const main = all.filter((t) => t.path[0] !== 'translucency' || t.path[1] === 'solid');
    const reduced = all.filter((t) => ext(t).reducedMotion !== undefined);
    const coarse = all.filter((t) => ext(t).coarsePointer !== undefined);

    const out = [banner(options.title)];
    const selectors = options.selectors.join(',\n');
    const indent = (block, pad) => block.replace(/^/gm, pad);

    out.push(`${selectors} {`);
    if (options.prelude) out.push(`  ${options.prelude}`);
    out.push(declarations(main), '}\n');

    if (reduced.length) {
      out.push(
        '/* §8.5: all three durations collapse to 0ms under reduced motion. */',
        '@media (prefers-reduced-motion: reduce) {',
        indent(`${selectors} {`, '  '),
        reduced.map((t) => `    --${t.name}: ${ext(t).reducedMotion};`).join('\n'),
        '  }',
        '}\n',
      );
    }

    if (coarse.length) {
      out.push(
        '/* Touch targets. `pointer: coarse` is the primary pointer being a finger,',
        ' * which is the Android build and a Mac in tablet-mirroring — not a screen',
        ' * width, because a narrow window on a Mac is still driven by a mouse. */',
        '@media (pointer: coarse) {',
        indent(`${selectors} {`, '  '),
        coarse.map((t) => `    --${t.name}: ${ext(t).coarsePointer};`).join('\n'),
        '  }',
        '}\n',
      );
    }

    if (frosted.length) {
      const on = options.selectors.map((s) => `${s}[data-translucency="on"]`).join(',\n');
      out.push(
        '/* §8.6: solid is the baseline. Frosting is additive inside @supports, so an',
        ' * engine without backdrop-filter gets the solid fallback with no separate',
        ' * rule and no lower-specificity rule for the on-state to defeat. */',
        '@supports (backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px)) {',
        indent(`${on} {`, '  '),
        frosted.map((t) => `    --${t.name}: ${t.$value ?? t.value};`).join('\n'),
        '  }\n',
        '  /* Authored last at the same specificity, so it wins wherever it matches. */',
        '  @media (prefers-reduced-transparency: reduce) {',
        indent(`${on} {`, '    '),
        solid.map((t) => `      --${t.name}: ${t.$value ?? t.value};`).join('\n'),
        '    }',
        '  }',
        '}\n',
      );
    }

    return out.join('\n');
  },
});

/** One complete product palette per theme, resolved for a colour scheme. */
StyleDictionary.registerFormat({
  name: 'css/copypaste-themes',
  format({ dictionary, options }) {
    const all = dictionary.allTokens;
    const scheme = all.filter((token) => token.path[0] === 'color');
    const recipes = all.filter((token) => token.path[0] === 'recipe');
    const themeRecipes = recipes.filter((token) => token.path[1] === 'theme');
    const byTheme = new Map();
    for (const token of all.filter((candidate) => candidate.path[0] === 'themes')) {
      const theme = token.path[1];
      if (!byTheme.has(theme)) byTheme.set(theme, []);
      byTheme.get(theme).push(token);
    }
    const blocks = [...byTheme].map(([theme, tokens]) => {
      const selectors = options.selectors(theme).join(',\n');
      const context = [...scheme, ...tokens, ...recipes];
      return `${selectors} {\n${declarations([...tokens, ...themeRecipes], context)}\n}`;
    });
    return [banner(options.title), blocks.join('\n\n'), ''].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'css/copypaste-swatches',
  format({ dictionary, options }) {
    const swatches = new Map();
    for (const token of dictionary.allTokens) {
      if (token.path[0] !== 'themes') continue;
      const [_, theme, role] = token.path;
      if (!swatches.has(theme)) swatches.set(theme, new Map());
      swatches.get(theme).set(role, token.$value ?? token.value);
    }

    const selectors = options.selectors.join(',\n');
    const declarations = [...swatches].flatMap(([theme, roles]) => [
      `  --preview-${theme}-canvas: ${roles.get('bg')};`,
      `  --preview-${theme}-rail: ${roles.get('panel')};`,
      `  --preview-${theme}-card: ${roles.get('elevated')};`,
      `  --preview-${theme}-muted: ${roles.get('raised-2')};`,
      `  --preview-${theme}-accent: ${roles.get('accent')};`,
    ]);
    return [banner(options.title), `${selectors} {`, declarations.join('\n'), '}\n'].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'css/copypaste-index',
  format({ options }) {
    return `${banner(options.title)}
/* Import order is the cascade. Base and scheme roles come first, then the
 * product-theme palettes and their generated previews. */
${options.imports.map((f) => `@import "./${f}";`).join('\n')}
`;
  },
});

/* ----------------------------------------------------------- platform setup */

const sources = (theme) => [
  `tokens/color/theme.${theme}.json`,
  `tokens/color/themes.${theme}.json`,
  'tokens/color/recipes.json',
  `tokens/color/recipes.${theme}.json`,
  `tokens/color/static.json`,
  `tokens/elevation.${theme}.json`,
  'tokens/elevation.static.json',
  'tokens/typography.json',
  'tokens/spacing.json',
  'tokens/radius.json',
  'tokens/motion.json',
  'tokens/size.json',
  'tokens/layout.json',
  'tokens/z-index.json',
  'tokens/translucency.json',
];

const CSS_TRANSFORMS = [
  'name/copypaste',
  'shadow/css/shorthand',
  'fontFamily/css',
  'cubicBezier/css',
];

/**
 * Palette values stay authored as-is. Only recipe tokens are resolved, in the
 * custom formats above, because old Android WebViews cannot parse color-mix().
 */
const cssPlatform = (theme, files) => ({
  transforms: CSS_TRANSFORMS,
  buildPath: DIST,
  files,
});

const themeConfig = (theme) => ({
  source: sources(theme),
  log: { verbosity: 'silent', warnings: 'warn' },
  platforms: {
    css: cssPlatform(theme, cssFiles(theme)),
  },
});

const themeSelectors = (theme) =>
  theme === 'dark'
    ? [':root', ':root[data-color-scheme="dark"]', '.theme-scope[data-color-scheme="dark"]']
    : [':root[data-color-scheme="light"]', '.theme-scope[data-color-scheme="light"]'];

const productThemeSelectors = (scheme, theme) => {
  const scoped = [
    `:root[data-color-scheme="${scheme}"][data-theme="${theme}"]`,
    `.theme-scope[data-color-scheme="${scheme}"][data-theme="${theme}"]`,
  ];
  return scheme === 'dark' && theme === 'midnight' ? [':root', ...scoped] : scoped;
};

function cssFiles(theme) {
  const files = [
    {
      destination: `css/tokens.${theme}.css`,
      format: 'css/copypaste',
      filter: (t) =>
        ((isThemed(t) && inGroup(t, 'color', 'elevation')) || inGroup(t, 'recipe'))
        && targets(t).includes('css'),
      options: {
        title: `CopyPaste ${theme} theme — shadcn/ui default theme, zinc base (OKLCH).`,
        selectors: themeSelectors(theme),
        prelude: `color-scheme: ${theme};`,
      },
    },
    {
      destination: `css/themes.${theme}.css`,
      format: 'css/copypaste-themes',
      filter: (t) =>
        (inGroup(t, 'themes', 'recipe') || (isThemed(t) && inGroup(t, 'color')))
        && targets(t).includes('css'),
      options: {
        title: `CopyPaste product themes resolved for ${theme} mode.`,
        selectors: (productTheme) => productThemeSelectors(theme, productTheme),
      },
    },
    {
      destination: `css/swatches.${theme}.css`,
      format: 'css/copypaste-swatches',
      filter: (t) => inGroup(t, 'themes'),
      options: {
        title: `CopyPaste theme previews, ${theme} — derived from the shipping palettes.`,
        selectors: themeSelectors(theme),
      },
    },
  ];
  if (theme !== 'dark') return files;
  return [
    {
      destination: 'css/tokens.base.css',
      format: 'css/copypaste',
      filter: (t) =>
        !isThemed(t) && !inGroup(t, 'tw', 'themes', 'recipe') && targets(t).includes('css'),
      options: {
        title: 'CopyPaste theme-independent tokens — type, space, radius, motion, size.',
        selectors: [':root'],
      },
    },
    ...files,
    {
      destination: 'css/index.css',
      format: 'css/copypaste-index',
      // The format emits imports, not tokens; the filter only has to be non-empty
      // so Style Dictionary writes the file.
      filter: (t) => inGroup(t, 'z'),
      options: {
        title: 'CopyPaste design tokens — entry point.',
        imports: [
          'tokens.base.css',
          'tokens.dark.css',
          'tokens.light.css',
          'themes.dark.css',
          'themes.light.css',
          'swatches.dark.css',
          'swatches.light.css',
        ],
      },
    },
  ];
}

/* ------------------------------------------------------------------- build */

const dark = new StyleDictionary(themeConfig('dark'));
const light = new StyleDictionary(themeConfig('light'));
await Promise.all([dark.hasInitialized, light.hasInitialized]);

await dark.buildAllPlatforms();
await light.buildPlatform('css');

await writeFile(
  `${DIST}README.txt`,
  'Everything in this directory is generated from design/tokens/ by Style Dictionary.\n' +
    'Do not edit it. Run `npm run build` in design/ instead.\n',
);

const [darkTokens, lightTokens] = await Promise.all([
  dark.getPlatformTokens('css'),
  light.getPlatformTokens('css'),
]);

console.log(
  `built ${darkTokens.allTokens.length} dark and ` +
    `${lightTokens.allTokens.length} light resolved tokens -> ${DIST}`,
);
