//! Deterministic TypeScript export for the WebView command boundary.

use std::path::Path;

use copypaste_ipc::{
    ConfigApplied, ConfigData, ConfigPatch, DiagnosticCounters, DiscoveredDevice, ErrorCode,
    ImportData, Liveness, PeerInfo, StatusData,
};
use ts_rs::{Config, ExportError, TS};

use crate::backend::UiError;
use crate::commands::transfer::{ExportReport, ImportPreview};
use crate::model::{UiItem, UiPage, UiSyncResult};
use crate::service::ServiceState;

/// Export every Rust-owned DTO into one checked-in frontend module.
pub fn export(out_dir: impl AsRef<Path>) -> Result<(), ExportError> {
    let config = Config::new()
        // serde_json/Tauri encode every integer as a JavaScript number. Using
        // ts-rs's bigint default would describe a value the bridge never emits.
        .with_large_int("number");

    let mut output =
        String::from("// This file was generated by ts-rs 12.0.1. Do not edit manually.\n\n");
    declaration::<ConfigApplied>(&config, &mut output);
    declaration::<ConfigData>(&config, &mut output);
    declaration::<ConfigPatch>(&config, &mut output);
    declaration::<DiagnosticCounters>(&config, &mut output);
    declaration::<DiscoveredDevice>(&config, &mut output);
    declaration::<ErrorCode>(&config, &mut output);
    declaration::<ExportReport>(&config, &mut output);
    declaration::<ImportData>(&config, &mut output);
    declaration::<ImportPreview>(&config, &mut output);
    declaration::<UiItem>(&config, &mut output);
    declaration::<UiPage>(&config, &mut output);
    declaration::<Liveness>(&config, &mut output);
    declaration::<PeerInfo>(&config, &mut output);
    declaration::<ServiceState>(&config, &mut output);
    declaration::<StatusData>(&config, &mut output);
    declaration::<UiSyncResult>(&config, &mut output);
    declaration::<UiError>(&config, &mut output);

    std::fs::create_dir_all(out_dir.as_ref())?;
    std::fs::write(out_dir.as_ref().join("ipc.ts"), output)?;
    Ok(())
}

fn declaration<T: TS>(config: &Config, output: &mut String) {
    let decl = strip_jsdoc(&T::decl(config));
    let compact = decl.split_whitespace().collect::<Vec<_>>().join(" ");
    output.push_str("export ");
    output.push_str(&compact);
    output.push_str("\n\n");
}

fn strip_jsdoc(source: &str) -> String {
    let mut rest = source;
    let mut output = String::with_capacity(source.len());
    while let Some(start) = rest.find("/**") {
        output.push_str(&rest[..start]);
        let Some(end) = rest[start + 3..].find("*/") else {
            break;
        };
        rest = &rest[start + 3 + end + 2..];
    }
    output.push_str(rest);
    output
}
