//! Deterministic TypeScript export for the WebView command boundary.

use std::path::Path;

use copypaste_ipc::{
    CloudStatusData, CloudSyncData, ConfigApplied, ConfigData, ConfigPatch, ContentClass,
    DeviceClass, DeviceDetails, DeviceEndpointObservation, DeviceLatencyObservation,
    DeviceObservationProvenance, DeviceObservationTrust, DevicePlatform, DevicePresence,
    DevicePresenceObservation, DeviceProfileObservation, DiagnosticCounters, DiscoveredDevice,
    ErrorCode, EventKind, ExternalNetworkObservation, ImportData, Liveness, PairingRole,
    PairingState, PeerInfo, PrivateModeData, SensitiveFinding, SensitiveSpan, SettingsHealth,
    StatusData,
};
use copypaste_runtime_log::{
    LogLevel as RuntimeLogLevel, Process as RuntimeLogProcess, RuntimeEvent as RuntimeLogEvent,
    RuntimeLogPage, RuntimeLogQuery,
};
use ts_rs::{Config, ExportError, TS};

use crate::backend::{UiBoundaryErrorCode, UiError};
use crate::capture::intake::CapturedPayload;
use crate::capture::model::{
    CaptureHealth, CaptureSnapshot, CaptureSource, NextStep, NotGrantedReason, NotWorkingReason,
    Rung, ShizukuProbe,
};
use crate::command_contract::UiCommandName;
use crate::commands::pairing::{PairedDevice, PairingCeremony};
use crate::commands::transfer::{ExportReport, ImportPreview};
use crate::events::TauriEventName;
use crate::model::{
    UiImagePreview, UiInstalledSourceApp, UiItem, UiPage, UiSourceAppIcon, UiSyncResult,
};
use crate::pairing_presentation::PairingPresentationState;
use crate::service::diagnostics::{Diagnostics, HistoryRead};
use crate::service::push::{ChangePayload, PushStatePayload};
use crate::service::ServiceState;
use crate::shell::appearance::NativeTheme;
use crate::shell::permissions::{
    OnboardingPermissions, PermissionHost, PermissionId, PermissionItem, PermissionStatus,
};
use crate::updater::{UpdateProgress, UpdateStatus};

/// Export every Rust-owned DTO into one checked-in frontend module.
pub fn export(out_dir: impl AsRef<Path>) -> Result<(), ExportError> {
    let config = Config::new()
        // serde_json/Tauri encode every integer as a JavaScript number. Using
        // ts-rs's bigint default would describe a value the bridge never emits.
        .with_large_int("number");

    let mut output =
        String::from("// This file was generated by ts-rs 12.0.1. Do not edit manually.\n\n");
    declaration::<ConfigApplied>(&config, &mut output);
    declaration::<CloudStatusData>(&config, &mut output);
    declaration::<CloudSyncData>(&config, &mut output);
    declaration::<ConfigData>(&config, &mut output);
    declaration::<ConfigPatch>(&config, &mut output);
    declaration::<ContentClass>(&config, &mut output);
    declaration::<Rung>(&config, &mut output);
    declaration::<CaptureSource>(&config, &mut output);
    declaration::<NotGrantedReason>(&config, &mut output);
    declaration::<NotWorkingReason>(&config, &mut output);
    declaration::<CaptureHealth>(&config, &mut output);
    declaration::<NextStep>(&config, &mut output);
    declaration::<ShizukuProbe>(&config, &mut output);
    declaration::<CaptureSnapshot>(&config, &mut output);
    declaration::<CapturedPayload>(&config, &mut output);
    declaration::<PermissionHost>(&config, &mut output);
    declaration::<PermissionId>(&config, &mut output);
    declaration::<PermissionStatus>(&config, &mut output);
    declaration::<PermissionItem>(&config, &mut output);
    declaration::<OnboardingPermissions>(&config, &mut output);
    declaration::<DiagnosticCounters>(&config, &mut output);
    declaration::<RuntimeLogProcess>(&config, &mut output);
    declaration::<RuntimeLogLevel>(&config, &mut output);
    declaration::<RuntimeLogEvent>(&config, &mut output);
    declaration::<RuntimeLogQuery>(&config, &mut output);
    declaration::<RuntimeLogPage>(&config, &mut output);
    declaration::<DeviceObservationProvenance>(&config, &mut output);
    declaration::<DeviceObservationTrust>(&config, &mut output);
    declaration::<DevicePlatform>(&config, &mut output);
    declaration::<DeviceClass>(&config, &mut output);
    declaration::<DeviceProfileObservation>(&config, &mut output);
    declaration::<DeviceEndpointObservation>(&config, &mut output);
    declaration::<DeviceLatencyObservation>(&config, &mut output);
    declaration::<DevicePresence>(&config, &mut output);
    declaration::<DevicePresenceObservation>(&config, &mut output);
    declaration::<ExternalNetworkObservation>(&config, &mut output);
    declaration::<DeviceDetails>(&config, &mut output);
    declaration::<DiscoveredDevice>(&config, &mut output);
    declaration::<ErrorCode>(&config, &mut output);
    declaration::<EventKind>(&config, &mut output);
    declaration::<TauriEventName>(&config, &mut output);
    declaration::<ChangePayload>(&config, &mut output);
    declaration::<PushStatePayload>(&config, &mut output);
    declaration::<ExportReport>(&config, &mut output);
    declaration::<ImportData>(&config, &mut output);
    declaration::<ImportPreview>(&config, &mut output);
    declaration::<UiImagePreview>(&config, &mut output);
    declaration::<UiSourceAppIcon>(&config, &mut output);
    declaration::<UiInstalledSourceApp>(&config, &mut output);
    declaration::<SensitiveSpan>(&config, &mut output);
    declaration::<SensitiveFinding>(&config, &mut output);
    declaration::<UiItem>(&config, &mut output);
    declaration::<UiPage>(&config, &mut output);
    declaration::<Liveness>(&config, &mut output);
    declaration::<PairingRole>(&config, &mut output);
    declaration::<PairingState>(&config, &mut output);
    declaration::<PairingPresentationState>(&config, &mut output);
    declaration::<PairedDevice>(&config, &mut output);
    declaration::<PairingCeremony>(&config, &mut output);
    declaration::<PeerInfo>(&config, &mut output);
    declaration::<PrivateModeData>(&config, &mut output);
    declaration::<ServiceState>(&config, &mut output);
    declaration::<HistoryRead>(&config, &mut output);
    declaration::<Diagnostics>(&config, &mut output);
    declaration::<SettingsHealth>(&config, &mut output);
    declaration::<StatusData>(&config, &mut output);
    declaration::<UiSyncResult>(&config, &mut output);
    declaration::<UiError>(&config, &mut output);
    declaration::<UiBoundaryErrorCode>(&config, &mut output);
    declaration::<UpdateStatus>(&config, &mut output);
    declaration::<UpdateProgress>(&config, &mut output);
    declaration::<NativeTheme>(&config, &mut output);
    runtime_metadata(&mut output);
    output.push_str("\nexport * from \"./ui-command-contract\";\n");

    let mut command_output = String::from(
        "// This file was generated by ts-rs 12.0.1. Do not edit manually.\n\nimport type { Channel } from \"@tauri-apps/api/core\";\nimport type { CaptureSnapshot, CaptureSource, CloudStatusData, CloudSyncData, ConfigApplied, ConfigPatch, Diagnostics, DiscoveredDevice, ExportReport, ImagePreview, ImportData, ImportPreview, InstalledSourceApp, Item, ItemPage, NativeTheme, OnboardingPermissionId, OnboardingPermissions, PairingCeremony, PeerInfo, PrivateModeData, RuntimeLogPage, RuntimeLogQuery, ServiceState, SourceAppIcon, StatusData, SyncResult, UpdateProgress, UpdateStatus } from \"./ipc\";\n\n",
    );
    command_contracts(&mut command_output);

    std::fs::create_dir_all(out_dir.as_ref())?;
    std::fs::write(out_dir.as_ref().join("ipc.ts"), output)?;
    std::fs::write(
        out_dir.as_ref().join("ui-command-contract.ts"),
        command_output,
    )?;
    std::fs::write(
        out_dir.as_ref().join("ui-command-inventory.json"),
        command_inventory(),
    )?;
    Ok(())
}

fn command_contracts(output: &mut String) {
    output.push_str("export const UI_COMMANDS = {\n");
    for command in UiCommandName::ALL {
        let name = command.as_str();
        output.push_str(&format!("  {name}: \"{name}\",\n"));
    }
    output.push_str("} as const;\n\n");
    output
        .push_str("export type UiCommandName = typeof UI_COMMANDS[keyof typeof UI_COMMANDS];\n\n");

    output.push_str("export interface UiCommandArgs {\n");
    for command in UiCommandName::ALL {
        output.push_str(&format!(
            "  {}: {};\n",
            command.as_str(),
            command.typescript_args()
        ));
    }
    output.push_str("}\n\n");
    output.push_str("export interface UiCommandResult {\n");
    for command in UiCommandName::ALL {
        output.push_str(&format!(
            "  {}: {};\n",
            command.as_str(),
            command.typescript_result()
        ));
    }
    output.push_str("}\n\n");
    output.push_str("export type CommandArgs<C extends UiCommandName> = UiCommandArgs[C];\n\n");
    output.push_str("export type CommandResult<C extends UiCommandName> = UiCommandResult[C];\n\n");

    output.push_str("export const NATIVE_UI_COMMAND_NAMES = [\n");
    for command in UiCommandName::NATIVE {
        output.push_str(&format!("  UI_COMMANDS.{},\n", command.as_str()));
    }
    output.push_str("] as const satisfies readonly UiCommandName[];\n");
}

fn runtime_metadata(output: &mut String) {
    output.push_str("export const TAURI_EVENTS = {\n");
    for event in TauriEventName::ALL {
        output.push_str(&format!(
            "  {}: \"{}\",\n",
            runtime_key(event.as_str()),
            event.as_str()
        ));
    }
    output.push_str("} as const satisfies Record<string, TauriEventName>;\n\n");
    output.push_str("export const TAURI_EVENT_NAMES = Object.values(TAURI_EVENTS);\n\n");
    output.push_str("export const UI_BOUNDARY_ERROR_CODES = {\n");
    for code in UiBoundaryErrorCode::ALL {
        output.push_str(&format!("  {}: \"{}\",\n", code.as_str(), code.as_str()));
    }
    output.push_str("} as const satisfies Record<string, UiBoundaryErrorCode>;\n\n");
    output.push_str(&format!(
        "export const CURRENT_PROTOCOL_VERSION = {} as const;\n",
        copypaste_ipc::PROTOCOL_VERSION
    ));
}

fn runtime_key(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect::<String>()
        .split('_')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("_")
}

fn command_inventory() -> String {
    let native_commands = UiCommandName::NATIVE
        .iter()
        .map(|command| command.as_str())
        .collect::<Vec<_>>();
    let preview_only_commands = UiCommandName::PREVIEW_ONLY
        .iter()
        .map(|command| command.as_str())
        .collect::<Vec<_>>();
    let value = serde_json::json!({
        "schema_version": 1,
        "native_commands": native_commands,
        "preview_only_commands": preview_only_commands,
    });
    format!("{}\n", serde_json::to_string_pretty(&value).unwrap())
}

fn declaration<T: TS>(config: &Config, output: &mut String) {
    let decl = strip_jsdoc(&T::decl(config));
    let compact = decl.split_whitespace().collect::<Vec<_>>().join(" ");
    output.push_str("export ");
    output.push_str(&compact);
    output.push_str("\n\n");
}

fn strip_jsdoc(source: &str) -> String {
    let mut rest = source;
    let mut output = String::with_capacity(source.len());
    while let Some(start) = rest.find("/**") {
        output.push_str(&rest[..start]);
        let Some(end) = rest[start + 3..].find("*/") else {
            break;
        };
        rest = &rest[start + 3 + end + 2..];
    }
    output.push_str(rest);
    output
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn capture_bindings_match_the_runtime_serialization_contract() {
        let out_dir = tempfile::tempdir().unwrap();
        export(out_dir.path()).unwrap();
        let generated = std::fs::read_to_string(out_dir.path().join("ipc.ts")).unwrap();
        let commands =
            std::fs::read_to_string(out_dir.path().join("ui-command-contract.ts")).unwrap();

        assert!(generated.contains(
            "export type CaptureHealth = { \"state\": \"not_granted\", reason: NotGrantedReason, } | { \"state\": \"disabled\" } | { \"state\": \"granted_not_working\", reason: NotWorkingReason, } | { \"state\": \"working\" };"
        ));
        assert!(generated.contains(
            "export type CaptureSnapshot = { rung: CaptureRung, health: CaptureHealth, shizuku: ShizukuProbe, nextStep: CaptureNextStep, headline: string, detail: string | null, lastReadOkAt: number | null, lastCaptureAt: number | null, droppedClips: number, toastSuppressed: boolean, toastAcknowledged: boolean, rearmRequested: boolean, };"
        ));
        assert!(generated.contains(
            "export type CapturedPayload = { id: string, source: CaptureSource, isSensitive: boolean, };"
        ));
        assert!(!generated.contains("export type Clip ="));
        assert!(generated.contains("export type PermissionHost ="));
        assert!(generated.contains(
            "export type ChangePayload = { topic: EventKind, item_count: number, swept: number, };"
        ));
        assert!(generated.contains("export * from \"./ui-command-contract\";"));
        assert!(!generated.contains("export const UI_COMMANDS = {"));
        assert!(commands.contains("export const UI_COMMANDS = {"));
        assert!(commands.contains("status: \"status\""));
        assert!(commands.contains("export interface UiCommandArgs {"));
        assert!(commands.contains("  list: { limit: number; cursor: string | null };"));
        assert!(commands.contains(
            "  install_update: { expectedVersion: string; progress: Channel<UpdateProgress> };"
        ));
        assert!(commands.contains("export interface UiCommandResult {"));
        assert!(commands.contains("  status: StatusData;"));
        assert!(commands.contains("  diagnostics: Diagnostics;"));
        assert!(!commands.contains(": unknown;"));
        assert!(generated.contains("export const CURRENT_PROTOCOL_VERSION = 2 as const;"));
        assert!(generated.contains("export type OnboardingPermissions ="));
        assert!(!generated.contains("export type ReadOutcome ="));

        let inventory =
            std::fs::read_to_string(out_dir.path().join("ui-command-inventory.json")).unwrap();
        let inventory: serde_json::Value = serde_json::from_str(&inventory).unwrap();
        assert_eq!(inventory["schema_version"], 1);
        assert!(inventory["native_commands"]
            .as_array()
            .unwrap()
            .iter()
            .any(|name| name == "status"));
        assert_eq!(
            inventory["preview_only_commands"],
            serde_json::json!(["pair_preview_invite", "pair_preview_join"])
        );

        let snapshot = CaptureSnapshot {
            rung: Rung::Shizuku,
            health: CaptureHealth::NotGranted {
                reason: NotGrantedReason::NoPermission,
            },
            shizuku: ShizukuProbe {
                supported: true,
                installed: true,
                running: true,
                permission: false,
                enabled: true,
                toast_suppressed: false,
                rearm_requested: true,
            },
            next_step: NextStep::GrantPermission,
            headline: "Background capture isn't set up.",
            detail: Some("Grant permission."),
            last_read_ok_at: None,
            last_capture_at: Some(1_700_000_000_000),
            dropped_clips: 2,
            toast_suppressed: false,
            toast_acknowledged: false,
            rearm_requested: true,
        };
        assert_eq!(
            serde_json::to_value(snapshot).unwrap(),
            json!({
                "rung": "shizuku",
                "health": { "state": "not_granted", "reason": "no_permission" },
                "shizuku": {
                    "supported": true,
                    "installed": true,
                    "running": true,
                    "permission": false,
                    "enabled": true,
                    "toastSuppressed": false,
                    "rearmRequested": true
                },
                "nextStep": "grant_permission",
                "headline": "Background capture isn't set up.",
                "detail": "Grant permission.",
                "lastReadOkAt": null,
                "lastCaptureAt": 1_700_000_000_000_i64,
                "droppedClips": 2,
                "toastSuppressed": false,
                "toastAcknowledged": false,
                "rearmRequested": true
            })
        );

        assert_eq!(
            serde_json::to_value(CapturedPayload {
                id: "item-1".into(),
                source: CaptureSource::ProcessText,
                is_sensitive: true,
            })
            .unwrap(),
            json!({ "id": "item-1", "source": "process_text", "isSensitive": true })
        );
    }
}
