FROM fedora:41@sha256:f1a3fab47bcb3c3ddf3135d5ee7ba8b7b25f2e809a47440936212a3a50957f3d
RUN dnf --assumeyes --setopt=install_weak_deps=False install dnf-plugins-core fedora-repos git meson ninja-build \
 && dnf config-manager --set-enabled fedora-source updates-source \
 && dnf builddep --assumeyes --setopt=install_weak_deps=False mutter \
 && dnf clean all
WORKDIR /workspace
