[package]
name = "copypaste-sensitive-rules"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
sha2.workspace = true
tokio.workspace = true
toml.workspace = true
