//! The real backend: `NSPasteboard`.
//!
//! CopyPaste develops on Linux, so this file neither compiles nor runs on the
//! host it is written on. The logic is manifest 01; the Cocoa spelling is not,
//! and the tests at the bottom are what settles it — they drive the real
//! general pasteboard on macOS CI, which is where `changeCount`, the `+2` of a
//! self-write, the opt-out markers and the size gate stop being API reading.
//! Anything they do not touch still is.
//!
//! # macOS 16 will make this read a user-visible event
//!
//! macOS 16 alerts the user when an app reads the general pasteboard
//! programmatically, and adds `NSPasteboard.accessBehavior` to request
//! always-allow. Every clipboard manager on the platform is affected; polling
//! `changeCount` without reading is not what trips it, `dataForType` is.
//!
//! Two things this is *not*. It is not the TCC problem in ADR-0001 — that one
//! comes from ad-hoc signing and is why the app needs no Accessibility
//! permission, whereas this arrives however the app is signed and cannot be
//! bought off with a Developer ID. And it is not a reason to poll less often:
//! the alert is about reading at all, so a slower loop would only make capture
//! worse without making the prompt rarer.
//!
//! Left as a note rather than an implementation because the API cannot be
//! exercised here and guessing at its shape is how a binding-level assumption
//! becomes a bug. Whoever first builds on macOS 16 should decide where the
//! always-allow request belongs — most likely the app at first run, not the
//! daemon mid-poll, since a prompt raised by a background process with no
//! window is a prompt with no context.

// objc2 0.2/0.5 marks a shifting set of pasteboard accessors `unsafe`.
// Wrapping every call and allowing the redundant ones keeps this module
// compiling across binding revisions instead of flipping with each bump.
#![allow(unused_unsafe)]

use objc2::rc::{autoreleasepool, Retained};
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};

use objc2_app_kit::{NSPasteboard, NSWorkspace};
use objc2_foundation::{NSArray, NSData, NSString};
use tracing::{debug, info, warn};

use super::change::{Change, ChangeTracker, SELF_WRITE_DELTA};
use super::{Capture, CapturePolicy, ClipboardSource, MAX_CAPTURE_BYTES};

/// UTIs spelled literally rather than pulled from `NSPasteboardType*`
/// statics: the values are frozen by the OS and by nspasteboard.org, and
/// this way the module does not depend on which binding revision exports
/// which constant.
const UTI_TEXT: &str = "public.utf8-plain-text";
const UTI_PNG: &str = "public.png";
const UTI_TIFF: &str = "public.tiff";
const UTI_FILE_URL: &str = "public.file-url";
const UTI_LEGACY_FILE_NAMES: &str = "NSFilenamesPboardType";
/// §3.4 — the three `org.nspasteboard.*` opt-out markers, probed as a set.
/// `ConcealedType` is how 1Password, Bitwarden, KeePassXC and friends say
/// "this is a secret, do not persist it". Ignoring these writes users'
/// master passwords into a searchable history.
const UTI_MARKERS: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

/// §3.12 (CopyPaste-pbre): the invariant UTI strings are process-lifetime
/// constants, built once and reused. v1 allocated ~12 fresh Cocoa strings on
/// every changed tick.
///
/// A `thread_local` rather than a `static`: these are strong references, so
/// they are deliberately *not* in the per-tick autorelease pool, and this
/// form needs no `Send`/`Sync` claim about `NSString` from whichever
/// binding revision is in the tree.
struct Utis {
    text: Retained<NSString>,
    text_probe: Retained<NSArray<NSString>>,
    png: Retained<NSString>,
    tiff: Retained<NSString>,
    image_probe: Retained<NSArray<NSString>>,
    file_url: Retained<NSString>,
    legacy_file_names: Retained<NSString>,
    markers: Retained<NSArray<NSString>>,
}

impl Utis {
    fn new() -> Self {
        let text = NSString::from_str(UTI_TEXT);
        let png = NSString::from_str(UTI_PNG);
        let tiff = NSString::from_str(UTI_TIFF);
        let file_url = NSString::from_str(UTI_FILE_URL);
        let legacy_file_names = NSString::from_str(UTI_LEGACY_FILE_NAMES);
        let markers: Vec<Retained<NSString>> =
            UTI_MARKERS.iter().map(|s| NSString::from_str(s)).collect();
        // `from_vec`, not `from_slice`: the latter needs `T: IsRetainable`, and
        // `NSString` is `ImmutableWithMutableSubclass<NSMutableString>`, which
        // is not. Taking owned `Retained`s is the supported path for it.
        Self {
            text_probe: NSArray::from_vec(vec![text.clone()]),
            image_probe: NSArray::from_vec(vec![png.clone(), tiff.clone()]),
            markers: NSArray::from_vec(markers),
            text,
            png,
            tiff,
            file_url,
            legacy_file_names,
        }
    }
}

thread_local! {
    static UTIS: Utis = Utis::new();
}

/// `NSPasteboard`-backed clipboard source.
///
/// Holds no Cocoa objects: the general pasteboard is a cheap singleton
/// lookup performed inside each poll's autorelease pool, which keeps this
/// type unconditionally `Send` for the poll task.
pub struct MacOsClipboard {
    tracker: ChangeTracker,
    rejected_too_large: u64,
    frontmost: Option<(Instant, Option<FrontmostApp>)>,
    last_attribution: Option<Attribution>,
    staging: super::file_materialize::StagingArea,
}

#[derive(Clone)]
struct FrontmostApp {
    /// Some foreground helpers do not advertise a bundle identifier even
    /// though AppKit can still tell us their localized name. Keep the two
    /// independently so the UI never turns a known source into “Unknown app”.
    bundle_id: Option<String>,
    name: Option<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Attribution {
    Bundle,
    NameOnly,
    Unavailable,
}

impl Attribution {
    fn from_app(app: Option<&FrontmostApp>) -> Self {
        match app {
            Some(FrontmostApp {
                bundle_id: Some(_), ..
            }) => Self::Bundle,
            Some(FrontmostApp { name: Some(_), .. }) => Self::NameOnly,
            _ => Self::Unavailable,
        }
    }
}

enum SelectedRepresentation {
    Data(Retained<NSData>, &'static str),
    LegacyFileNames(Retained<NSData>),
}

fn first_absolute_filename_plist(bytes: &[u8]) -> Option<PathBuf> {
    // `NSFilenamesPboardType` is a binary plist. Reject another encoding rather
    // than treating arbitrary text as a path, and let parser failures remain a
    // harmless dropped pasteboard change (CopyPaste-q5ab / I-37).
    if !bytes.starts_with(b"bplist00") {
        debug!("legacy filename pasteboard payload was not a binary plist; dropped");
        return None;
    }
    plist::from_bytes::<Vec<String>>(bytes)
        .ok()?
        .into_iter()
        .map(PathBuf::from)
        .find(|path| path.is_absolute())
}

fn file_capture(
    path: PathBuf,
    app_bundle_id: Option<String>,
    app_name: Option<String>,
) -> Option<Capture> {
    if !path.is_absolute() {
        debug!("pasteboard file path was not absolute; dropped");
        return None;
    }
    let filename = path.file_name()?.to_string_lossy().into_owned();
    let mime = mime_guess::from_path(&path)
        .first_raw()
        .unwrap_or("application/octet-stream");
    let metadata = copypaste_core::FileMetadata::new(filename, mime)?;
    Some(Capture {
        content: String::new(),
        binary_content: None,
        file_path: Some(path),
        file_metadata: Some(metadata),
        content_type: copypaste_ipc::content_type::FILE.to_string(),
        app_bundle_id,
        app_name,
    })
}

impl MacOsClipboard {
    pub fn new(data_dir: &Path) -> std::io::Result<Self> {
        Ok(Self {
            tracker: ChangeTracker::new(),
            rejected_too_large: 0,
            frontmost: None,
            last_attribution: None,
            staging: super::file_materialize::StagingArea::new(data_dir)?,
        })
    }
}

impl ClipboardSource for MacOsClipboard {
    fn poll(&mut self) -> Option<Capture> {
        let settings = copypaste_ipc::ConfigData::default();
        self.poll_with_policy(CapturePolicy::new(&settings))
    }

    fn poll_with_policy(&mut self, policy: CapturePolicy<'_>) -> Option<Capture> {
        // I-17: one autorelease pool around the entire Cocoa interaction.
        // Without it, autoreleased NSString/NSData accumulate on the async
        // worker thread and reserved memory grows without bound.
        autoreleasepool(|_pool| {
            let pb = unsafe { NSPasteboard::generalPasteboard() };

            // I-1: the change-count comparison is the first thing we do; an
            // unchanged pasteboard performs zero reads and zero allocations.
            let count = unsafe { pb.changeCount() } as i64;
            match self.tracker.observe(count) {
                Change::Unchanged => return None,
                Change::SelfWrite => {
                    debug!(change_count = count, "suppressed our own pasteboard write");
                    return None;
                }
                Change::Fresh { lost_intermediates } => {
                    if lost_intermediates > 0 {
                        // §3.1/§3.2: telemetry only. NSPasteboard keeps no
                        // history, so the intermediates are gone — but the
                        // surviving value is captured below, never replaced
                        // by a "burst happened" result.
                        warn!(
                            lost = lost_intermediates,
                            change_count = count,
                            "pasteboard burst: intermediate values are irrecoverable"
                        );
                    }
                }
            }

            // I-5 / §3.4: probe the opt-out markers BEFORE reading any
            // representation, so a password never enters process memory at
            // all. "Read then discard" is not compliant. A pasteboard
            // carrying a marker *and* a normal string is dropped entirely;
            // that is intentional.
            let marked =
                UTIS.with(|utis| unsafe { pb.availableTypeFromArray(&utis.markers).is_some() });
            if marked {
                // I-9: no content, no type name.
                debug!(
                    change_count = count,
                    "pasteboard change carries an org.nspasteboard.* opt-out marker; dropped"
                );
                return None;
            }

            // Private mode must be a capture gate, not merely an ingest choice:
            // acknowledge the change without reading either attribution or data.
            if policy.settings.private_mode {
                return None;
            }

            // Resolve attribution before choosing a representation. A non-empty
            // exclusion list fails closed when it cannot be resolved; with an
            // empty list the same `None` is safe because content detection
            // remains active. The 750 ms cache bounds stale exclusion decisions.
            let source_app = self.frontmost_app();
            self.note_attribution(source_app.as_ref());
            let app_bundle_id = source_app.as_ref().and_then(|app| app.bundle_id.clone());
            let app_name = source_app.and_then(|app| app.name);
            if !policy.settings.excluded_app_bundle_ids.is_empty()
                && app_bundle_id.as_ref().is_none_or(|id| {
                    policy
                        .settings
                        .excluded_app_bundle_ids
                        .iter()
                        .any(|excluded| excluded == id)
                })
            {
                return None;
            }

            let selected = UTIS.with(|utis| unsafe {
                if pb.availableTypeFromArray(&utis.text_probe).is_some() {
                    return pb.dataForType(&utis.text).map(|data| {
                        SelectedRepresentation::Data(data, copypaste_ipc::content_type::TEXT)
                    });
                }
                // I-12 probes presence before materialising data.  TIFF is
                // never queried when PNG exists, which preserves I-13.
                if pb.availableTypeFromArray(&utis.image_probe).is_some() {
                    if let Some(data) = pb.dataForType(&utis.png) {
                        return Some(SelectedRepresentation::Data(
                            data,
                            copypaste_ipc::content_type::IMAGE_PNG,
                        ));
                    }
                    return pb.dataForType(&utis.tiff).map(|data| {
                        SelectedRepresentation::Data(data, copypaste_ipc::content_type::IMAGE_TIFF)
                    });
                }
                if let Some(data) = pb.dataForType(&utis.file_url) {
                    return Some(SelectedRepresentation::Data(
                        data,
                        copypaste_ipc::content_type::FILE,
                    ));
                }
                pb.dataForType(&utis.legacy_file_names)
                    .map(SelectedRepresentation::LegacyFileNames)
            })?;
            let (data, content_type, legacy_file_names) = match selected {
                SelectedRepresentation::Data(data, content_type) => (data, content_type, false),
                SelectedRepresentation::LegacyFileNames(data) => {
                    (data, copypaste_ipc::content_type::FILE, true)
                }
            };

            // I-18 (CopyPaste-1f5c): `length` is a field read, `to_vec` on a
            // multi-GiB item is a multi-GiB allocation. Check first.
            let len = unsafe { data.length() };
            let cap =
                usize::try_from(policy.limit_bytes(content_type)).unwrap_or(MAX_CAPTURE_BYTES);
            if len > cap {
                self.rejected_too_large += 1;
                // I-39 / §6.5: counted, not silently dropped.
                warn!(
                    bytes = len,
                    cap, "pasteboard representation exceeds the size cap; dropped"
                );
                return None;
            }

            let bytes = unsafe { data.bytes() }.to_vec();
            // public.utf8-plain-text is UTF-8 by definition; malformed input
            // is a third-party app's bug. §3.6's precedent is lossy
            // conversion rather than dropping the user's copy, and I-37
            // forbids panicking on a malformed payload.
            if content_type == copypaste_ipc::content_type::TEXT {
                let content = String::from_utf8_lossy(&bytes).into_owned();
                if content.is_empty() {
                    return None;
                }
                Some(Capture {
                    content,
                    binary_content: None,
                    file_path: None,
                    file_metadata: None,
                    content_type: content_type.to_string(),
                    app_bundle_id,
                    app_name,
                })
            } else if content_type == copypaste_ipc::content_type::FILE {
                let path = if legacy_file_names {
                    first_absolute_filename_plist(&bytes)?
                } else {
                    let Ok(url) = url::Url::parse(&String::from_utf8_lossy(&bytes)) else {
                        return None;
                    };
                    let Ok(path) = url.to_file_path() else {
                        return None;
                    };
                    path
                };
                file_capture(path, app_bundle_id, app_name)
            } else {
                Some(Capture {
                    content: String::new(),
                    binary_content: Some(bytes),
                    file_path: None,
                    file_metadata: None,
                    content_type: content_type.to_string(),
                    app_bundle_id,
                    app_name,
                })
            }
        })
    }

    fn changed(&mut self) -> bool {
        autoreleasepool(|_pool| {
            let pb = unsafe { NSPasteboard::generalPasteboard() };
            !self.tracker.is_current(unsafe { pb.changeCount() } as i64)
        })
    }

    fn set_contents(&mut self, text: &str) -> anyhow::Result<()> {
        // I-17 again: the paste-back path needs the pool as much as the poll.
        autoreleasepool(|_pool| {
            let pb = unsafe { NSPasteboard::generalPasteboard() };
            let pre = unsafe { pb.changeCount() } as i64;

            let value = NSString::from_str(text);
            let ok = UTIS.with(|utis| unsafe {
                // §3.3 step 2, armed from the count `clearContents` returns
                // rather than a predicted one, and before `setString` makes the
                // content visible. A poll landing between the two sees an empty
                // pasteboard, which yields nothing and keeps polling.
                self.tracker.sentinel.arm(pb.clearContents() as i64);
                pb.setString_forType(&value, &utis.text)
            });
            if !ok {
                // §3.3 step 5.
                self.tracker.sentinel.clear();
                // I-9 / CLAUDE.md rule 4: no paths, no content.
                return Err(anyhow::anyhow!("the pasteboard rejected the write"));
            }

            // CopyPaste-8yzf: a third-party write landing in the middle leaves
            // the armed count below the current one, where it can never match.
            // There is nothing to repair — reported, not corrected, because
            // correcting it is what would suppress their content as ours.
            let actual = unsafe { pb.changeCount() } as i64;
            if actual != pre + SELF_WRITE_DELTA {
                debug!(
                    expected = pre + SELF_WRITE_DELTA,
                    actual, "another app wrote to the pasteboard during our write"
                );
            }
            Ok(())
        })
    }

    fn set_binary_contents(
        &mut self,
        _item_id: &str,
        content_type: &str,
        bytes: &[u8],
        metadata: Option<&copypaste_core::FileMetadata>,
    ) -> anyhow::Result<()> {
        let uti = match content_type {
            copypaste_ipc::content_type::IMAGE_PNG => UTI_PNG,
            copypaste_ipc::content_type::IMAGE_TIFF => UTI_TIFF,
            copypaste_ipc::content_type::FILE => UTI_FILE_URL,
            _ => {
                return Err(anyhow::anyhow!(
                    "the pasteboard cannot write this binary content type"
                ));
            }
        };
        let file_url = if content_type == copypaste_ipc::content_type::FILE {
            let metadata =
                metadata.ok_or_else(|| anyhow::anyhow!("file metadata is unavailable"))?;
            let path = self.staging.materialize(bytes, metadata)?;
            Some(
                url::Url::from_file_path(path)
                    .map_err(|_| anyhow::anyhow!("could not materialize file paste"))?,
            )
        } else {
            None
        };
        autoreleasepool(|_pool| {
            let pb = unsafe { NSPasteboard::generalPasteboard() };
            let pre = unsafe { pb.changeCount() } as i64;
            let bytes = file_url
                .as_ref()
                .map_or(bytes, |url| url.as_str().as_bytes());
            let data = unsafe {
                NSData::dataWithBytes_length(bytes.as_ptr().cast_mut().cast(), bytes.len())
            };
            let uti = NSString::from_str(uti);
            self.tracker
                .sentinel
                .arm(unsafe { pb.clearContents() } as i64);
            if !unsafe { pb.setData_forType(Some(&data), &uti) } {
                self.tracker.sentinel.clear();
                return Err(anyhow::anyhow!("the pasteboard rejected the binary write"));
            }
            let actual = unsafe { pb.changeCount() } as i64;
            if actual != pre + SELF_WRITE_DELTA {
                self.tracker.sentinel.clear();
            }
            Ok(())
        })
    }

    fn backend_name(&self) -> &'static str {
        "nspasteboard"
    }

    fn rejected_too_large_count(&self) -> u64 {
        self.rejected_too_large
    }

    fn lost_intermediates_count(&self) -> u64 {
        self.tracker.lost_intermediates
    }
}

impl MacOsClipboard {
    fn note_attribution(&mut self, app: Option<&FrontmostApp>) {
        let attribution = Attribution::from_app(app);
        if self.last_attribution == Some(attribution) {
            return;
        }
        self.last_attribution = Some(attribution);
        match attribution {
            Attribution::Bundle => info!("macOS capture source attribution is available"),
            Attribution::NameOnly => {
                info!("macOS capture source attribution is available without a bundle identifier")
            }
            Attribution::Unavailable => {
                warn!("macOS could not identify the source application for clipboard capture")
            }
        }
    }

    fn frontmost_app(&mut self) -> Option<FrontmostApp> {
        if let Some((seen, app)) = &self.frontmost {
            if seen.elapsed() < Duration::from_millis(750) {
                return app.clone();
            }
        }
        let app = unsafe {
            NSWorkspace::sharedWorkspace()
                .frontmostApplication()
                .and_then(|app| {
                    let bundle_id = app.bundleIdentifier().map(|id| id.to_string());
                    let name = app.localizedName().map(|name| name.to_string());
                    // A foreground application can be an unbundled helper.
                    // It has neither value only when AppKit genuinely cannot
                    // attribute the foreground process.
                    (bundle_id.is_some() || name.is_some())
                        .then_some(FrontmostApp { bundle_id, name })
                })
        };
        self.frontmost = Some((Instant::now(), app.clone()));
        app
    }
}

// ---------------------------------------------------------------------------
// Tests — the half of manifest 01 that only a Mac can answer
// ---------------------------------------------------------------------------
//
// `super::change` made the state machine testable anywhere. What stayed
// untestable is this file: whether `changeCount` moves at all without a window
// server, whether `clearContents` + `setString:forType:` is really the +2 of
// §4, and whether `availableTypeFromArray` sees the markers a password manager
// writes. Each is an assumption about the bindings, and each one wrong breaks a
// rule the manifest records a production bug for.
//
// `#[ignore]`: the general pasteboard is the machine's own clipboard, so a run
// replaces whatever was copied. Serialised for the reason §5 gives — it is a
// process-global singleton — by a mutex here as well as `--test-threads=1` in
// CI, so a plain `cargo test -- --ignored` is not silently racy.

#[cfg(test)]
mod tests {
    use std::sync::{Mutex, MutexGuard};

    use objc2_foundation::NSData;

    use super::*;

    static PASTEBOARD: Mutex<()> = Mutex::new(());

    fn serialised() -> MutexGuard<'static, ()> {
        PASTEBOARD.lock().unwrap_or_else(|held| held.into_inner())
    }

    fn test_clipboard() -> (tempfile::TempDir, MacOsClipboard) {
        let data_dir = tempfile::tempdir().unwrap();
        let clipboard = MacOsClipboard::new(data_dir.path()).unwrap();
        (data_dir, clipboard)
    }

    fn change_count() -> i64 {
        autoreleasepool(|_| unsafe { NSPasteboard::generalPasteboard().changeCount() as i64 })
    }

    /// What another application does: `clearContents` and then one `setData`
    /// per representation it offers.
    fn write_types(reps: &[(&str, &[u8])]) {
        autoreleasepool(|_| unsafe {
            let pb = NSPasteboard::generalPasteboard();
            let _ = pb.clearContents();
            for &(uti, bytes) in reps {
                let data = NSData::with_bytes(bytes);
                let _ = pb.setData_forType(Some(&data), &NSString::from_str(uti));
            }
        });
    }

    /// Whether the pasteboard offers a UTI — the same question the poll asks,
    /// so a test can assert its own precondition instead of trusting the
    /// return value of `setData:forType:`.
    fn offers(uti: &str) -> bool {
        autoreleasepool(|_| unsafe {
            let types = NSArray::from_vec(vec![NSString::from_str(uti)]);
            NSPasteboard::generalPasteboard()
                .availableTypeFromArray(&types)
                .is_some()
        })
    }

    fn write_text(text: &str) {
        write_types(&[(UTI_TEXT, text.as_bytes())]);
        assert!(offers(UTI_TEXT), "the pasteboard refused a test write");
    }

    fn clear() {
        autoreleasepool(|_| unsafe {
            let _ = NSPasteboard::generalPasteboard().clearContents();
        });
    }

    #[test]
    fn legacy_filenames_binary_plist_uses_the_first_absolute_path() {
        let mut bytes = Vec::new();
        plist::to_writer_binary(
            &mut bytes,
            &vec!["relative.txt", "/Users/example/Report.pdf", "/ignored.txt"],
        )
        .unwrap();

        assert_eq!(
            first_absolute_filename_plist(&bytes),
            Some(PathBuf::from("/Users/example/Report.pdf"))
        );
    }

    #[test]
    fn malformed_or_non_binary_legacy_filename_data_is_dropped() {
        assert!(first_absolute_filename_plist(b"/Users/example/Report.pdf").is_none());
        assert!(first_absolute_filename_plist(b"bplist00not-a-plist").is_none());
    }

    #[test]
    fn file_capture_uses_the_extension_mime_and_never_retains_the_full_path() {
        let capture = file_capture(PathBuf::from("/Users/example/Report.pdf"), None, None).unwrap();
        assert_eq!(
            capture.file_path,
            Some(PathBuf::from("/Users/example/Report.pdf"))
        );
        assert_eq!(
            capture.file_metadata,
            Some(copypaste_core::FileMetadata::new("Report.pdf", "application/pdf").unwrap())
        );
    }

    #[test]
    fn source_attribution_preserves_a_name_when_a_helper_has_no_bundle_id() {
        assert_eq!(
            Attribution::from_app(Some(&FrontmostApp {
                bundle_id: None,
                name: Some("Helper".to_owned()),
            })),
            Attribution::NameOnly
        );
    }

    #[test]
    #[ignore = "drives the real NSPasteboard"]
    fn file_write_uses_the_active_data_directory_and_preserves_the_filename() {
        let _lock = serialised();
        let data_dir = tempfile::tempdir().unwrap();
        let mut clipboard = MacOsClipboard::new(data_dir.path()).unwrap();
        let metadata =
            copypaste_core::FileMetadata::new("Résumé 2026.pdf", "application/pdf").unwrap();

        clipboard
            .set_binary_contents(
                "untrusted-remote-id",
                copypaste_ipc::content_type::FILE,
                b"decrypted file bytes",
                Some(&metadata),
            )
            .unwrap();

        let path = autoreleasepool(|_| unsafe {
            let bytes = UTIS.with(|utis| {
                NSPasteboard::generalPasteboard()
                    .dataForType(&utis.file_url)
                    .expect("the file URL was not put on the pasteboard")
                    .bytes()
                    .to_vec()
            });
            let url = url::Url::parse(&String::from_utf8(bytes).unwrap()).unwrap();
            url.to_file_path().unwrap()
        });
        assert!(path.starts_with(data_dir.path().join("paste-files")));
        assert_eq!(path.file_name().unwrap(), "Résumé 2026.pdf");
        assert_eq!(std::fs::read(path).unwrap(), b"decrypted file bytes");
    }

    /// T-21, T-4, I-1, I-2. Also the first question of all: does `changeCount`
    /// move on a headless runner?
    #[test]
    #[ignore = "drives the real NSPasteboard"]
    fn a_change_by_another_app_is_captured_exactly_once() {
        let _lock = serialised();
        let (_data_dir, mut clipboard) = test_clipboard();

        let before = change_count();
        write_text("copypaste — a check ✓");
        let after = change_count();
        assert!(
            after > before,
            "changeCount did not move for a write ({before} -> {after}); \
             nothing in this backend can work if it does not"
        );

        let capture = clipboard.poll().expect("the write must be captured");
        assert_eq!(capture.content, "copypaste — a check ✓");
        assert_eq!(capture.content_type, copypaste_ipc::content_type::TEXT);
        assert_eq!(
            clipboard.lost_intermediates_count(),
            0,
            "I-2: a first poll at an arbitrary change count is not a burst"
        );

        assert!(
            clipboard.poll().is_none(),
            "T-4: an unchanged pasteboard must yield nothing"
        );
    }

    /// §4's self-write delta, which is a *prediction*: the sentinel is armed
    /// at `pre + SELF_WRITE_DELTA` before the write, so a wrong number arms it
    /// at a change count that never arrives.
    ///
    /// Split from the suppression test below deliberately. This one says what
    /// the OS does; that one says what our protocol does with it. Running them
    /// together let the first assertion mask the second, and the second is the
    /// one that names the user-visible bug.
    #[test]
    #[ignore = "drives the real NSPasteboard"]
    fn a_self_write_moves_the_count_by_the_predicted_delta() {
        let _lock = serialised();
        let (_data_dir, mut clipboard) = test_clipboard();
        write_text("something copied earlier");
        let _ = clipboard.poll();

        let pre = change_count();
        clipboard
            .set_contents("pasted by us")
            .expect("the write failed");
        let actual = change_count();
        assert_eq!(
            actual - pre,
            SELF_WRITE_DELTA,
            "§4 predicts clearContents (+1) then setString:forType: (+1). \
             Observed {pre} -> {actual}: the sentinel is armed at {} and the \
             write lands on {actual}, so nothing is ever suppressed",
            pre + SELF_WRITE_DELTA
        );
    }

    /// T-8, T-9 and the Fix-4 / "DUP-ON-COPY" pair, asserted as behaviour
    /// rather than as arithmetic: whatever the delta turns out to be, our own
    /// write must not come back, and the next genuine copy must.
    #[test]
    #[ignore = "drives the real NSPasteboard"]
    fn our_own_write_is_suppressed_and_the_next_genuine_copy_is_not() {
        let _lock = serialised();
        let (_data_dir, mut clipboard) = test_clipboard();
        write_text("something copied earlier");
        let _ = clipboard.poll();

        clipboard
            .set_contents("pasted by us")
            .expect("the write failed");
        if let Some(capture) = clipboard.poll() {
            panic!(
                "T-8: our own paste-back came back as a capture ({:?}) — this is \
                 the duplicate-on-copy bug, and the sentinel is now armed at a \
                 count no write of ours will reach",
                capture.content
            );
        }

        write_text("a genuine copy");
        assert_eq!(
            clipboard
                .poll()
                .expect(
                    "T-9: a genuine copy was swallowed — a sentinel that was never \
                     consumed suppresses whichever real copy lands on it"
                )
                .content,
            "a genuine copy"
        );
    }

    /// §3.2, the manifest's highest-value rule: a burst must never be returned
    /// *instead of* the surviving value. T-5, T-6.
    #[test]
    #[ignore = "drives the real NSPasteboard"]
    fn a_burst_reports_its_losses_and_still_returns_the_survivor() {
        let _lock = serialised();
        let (_data_dir, mut clipboard) = test_clipboard();
        write_text("seed");
        let _ = clipboard.poll();

        write_text("one");
        write_text("two");
        write_text("latest");

        let capture = clipboard
            .poll()
            .expect("§3.2: the surviving clipboard value must still be captured");
        assert_eq!(capture.content, "latest");
        let lost = clipboard.lost_intermediates_count();
        assert!(lost > 0, "the burst must be reported as telemetry");

        write_text("after-burst");
        assert_eq!(
            clipboard
                .poll()
                .expect("T-6: normal capture resumes")
                .content,
            "after-burst"
        );
        assert_eq!(clipboard.lost_intermediates_count(), lost);
    }

    /// I-5, §3.4, T-14, T-15, T-16. The marker is written *alongside* ordinary
    /// text, which is the shape a password manager produces and the case that
    /// must still be dropped entirely.
    #[test]
    #[ignore = "drives the real NSPasteboard"]
    fn every_opt_out_marker_drops_the_change_and_advances_the_cursor() {
        let _lock = serialised();
        let (_data_dir, mut clipboard) = test_clipboard();

        for marker in UTI_MARKERS {
            // Empty content, which is how the convention is written in the
            // wild; presence of the type is the whole signal.
            write_types(&[(UTI_TEXT, b"a master password"), (marker, b"")]);
            assert!(
                offers(marker),
                "{marker} could not be put on the pasteboard"
            );
            assert!(
                clipboard.poll().is_none(),
                "{marker} did not suppress the change"
            );
            assert!(
                clipboard.poll().is_none(),
                "I-3: {marker} left the change to be re-offered forever"
            );
        }

        write_text("an ordinary copy");
        assert_eq!(
            clipboard
                .poll()
                .expect("a marked change must not wedge the poll")
                .content,
            "an ordinary copy"
        );
    }

    /// I-18, I-39, T-30, T-33. §6.5 is the reason the counter is asserted and
    /// not just the rejection: v1 wired a counter that nothing read and that
    /// the image path bypassed, so an oversized item vanished in silence.
    #[test]
    #[ignore = "drives the real NSPasteboard"]
    fn text_over_the_cap_is_rejected_and_counted_and_the_boundary_is_kept() {
        let _lock = serialised();
        let (_data_dir, mut clipboard) = test_clipboard();

        let oversized = vec![b'a'; MAX_CAPTURE_BYTES + 1];
        write_types(&[(UTI_TEXT, &oversized)]);
        assert!(offers(UTI_TEXT), "the oversized write never landed");
        assert!(clipboard.poll().is_none(), "T-30: over the cap by one byte");
        assert_eq!(
            clipboard.rejected_too_large_count(),
            1,
            "I-39: a rejection must be counted, not only logged"
        );

        let at_the_cap = vec![b'a'; MAX_CAPTURE_BYTES];
        write_types(&[(UTI_TEXT, &at_the_cap)]);
        assert!(offers(UTI_TEXT), "the boundary write never landed");
        let capture = clipboard.poll().expect("T-33: len == cap is accepted");
        assert_eq!(capture.content.len(), MAX_CAPTURE_BYTES);
        assert_eq!(clipboard.rejected_too_large_count(), 1);
    }

    #[test]
    #[ignore = "drives the real NSPasteboard"]
    fn image_pre_read_uses_the_image_limit_and_keeps_its_boundary() {
        let _lock = serialised();
        let (_data_dir, mut clipboard) = test_clipboard();
        let settings = copypaste_ipc::ConfigData {
            max_image_size_bytes: copypaste_ipc::MIN_IMAGE_SIZE_BYTES,
            ..Default::default()
        };

        let oversized = vec![0; copypaste_ipc::MIN_IMAGE_SIZE_BYTES as usize + 1];
        write_types(&[(UTI_PNG, &oversized)]);
        assert!(clipboard
            .poll_with_policy(CapturePolicy::new(&settings))
            .is_none());

        let boundary = vec![0; copypaste_ipc::MIN_IMAGE_SIZE_BYTES as usize];
        write_types(&[(UTI_PNG, &boundary)]);
        let capture = clipboard
            .poll_with_policy(CapturePolicy::new(&settings))
            .expect("the encoded-image boundary is accepted");
        assert_eq!(capture.binary_content.as_deref(), Some(boundary.as_slice()));
    }

    /// An empty pasteboard is a change like any other: nothing to capture, and
    /// the cursor still moves (I-3).
    #[test]
    #[ignore = "drives the real NSPasteboard"]
    fn a_cleared_pasteboard_yields_nothing_and_keeps_polling() {
        let _lock = serialised();
        let (_data_dir, mut clipboard) = test_clipboard();
        write_text("before the clear");
        let _ = clipboard.poll();

        clear();
        assert!(clipboard.poll().is_none());
        assert!(clipboard.poll().is_none());

        write_text("after the clear");
        assert_eq!(
            clipboard.poll().expect("capture must resume").content,
            "after the clear"
        );
    }
}
