//! The real backend: `NSPasteboard`.
//!
//! **Unverified on this host.** CopyPaste develops on Linux; nothing in this
//! file has been compiled or run. The logic is written against manifest 01 and
//! the shared [`ChangeTracker`] it uses *is* tested — that is the whole reason
//! change detection lives in [`super::change`] rather than here.
//!
//! Binding-level assumptions to confirm on a mac (the *logic* is manifest, the
//! *spelling* is not): `NSPasteboard::generalPasteboard`, `changeCount`,
//! `clearContents`, `availableTypeFromArray`, `dataForType`, `setString_forType`,
//! `NSArray::from_slice`, `NSData::length`/`bytes`.
//!
//! # macOS 16 will make this read a user-visible event
//!
//! macOS 16 alerts the user when an app reads the general pasteboard
//! programmatically, and adds `NSPasteboard.accessBehavior` to request
//! always-allow. Every clipboard manager on the platform is affected; polling
//! `changeCount` without reading is not what trips it, `dataForType` is.
//!
//! Two things this is *not*. It is not the TCC problem in ADR-0001 — that one
//! comes from ad-hoc signing and is why the app needs no Accessibility
//! permission, whereas this arrives however the app is signed and cannot be
//! bought off with a Developer ID. And it is not a reason to poll less often:
//! the alert is about reading at all, so a slower loop would only make capture
//! worse without making the prompt rarer.
//!
//! Left as a note rather than an implementation because the API cannot be
//! exercised here and guessing at its shape is how a binding-level assumption
//! becomes a bug. Whoever first builds on macOS 16 should decide where the
//! always-allow request belongs — most likely the app at first run, not the
//! daemon mid-poll, since a prompt raised by a background process with no
//! window is a prompt with no context.

// objc2 0.2/0.5 marks a shifting set of pasteboard accessors `unsafe`.
// Wrapping every call and allowing the redundant ones keeps this module
// compiling across binding revisions instead of flipping with each bump.
#![allow(unused_unsafe)]

use objc2::rc::{autoreleasepool, Retained};
use objc2_app_kit::NSPasteboard;
use objc2_foundation::{NSArray, NSString};
use tracing::{debug, warn};

use super::change::{Change, ChangeTracker, SELF_WRITE_DELTA};
use super::{Capture, ClipboardSource, MAX_TEXT_BYTES};

/// UTIs spelled literally rather than pulled from `NSPasteboardType*`
/// statics: the values are frozen by the OS and by nspasteboard.org, and
/// this way the module does not depend on which binding revision exports
/// which constant.
const UTI_TEXT: &str = "public.utf8-plain-text";
/// §3.4 — the three `org.nspasteboard.*` opt-out markers, probed as a set.
/// `ConcealedType` is how 1Password, Bitwarden, KeePassXC and friends say
/// "this is a secret, do not persist it". Ignoring these writes users'
/// master passwords into a searchable history.
const UTI_MARKERS: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

/// §3.12 (CopyPaste-pbre): the invariant UTI strings are process-lifetime
/// constants, built once and reused. v1 allocated ~12 fresh Cocoa strings on
/// every changed tick.
///
/// A `thread_local` rather than a `static`: these are strong references, so
/// they are deliberately *not* in the per-tick autorelease pool, and this
/// form needs no `Send`/`Sync` claim about `NSString` from whichever
/// binding revision is in the tree.
struct Utis {
    text: Retained<NSString>,
    text_probe: Retained<NSArray<NSString>>,
    markers: Retained<NSArray<NSString>>,
}

impl Utis {
    fn new() -> Self {
        let text = NSString::from_str(UTI_TEXT);
        let markers: Vec<Retained<NSString>> =
            UTI_MARKERS.iter().map(|s| NSString::from_str(s)).collect();
        let marker_refs: Vec<&NSString> = markers.iter().map(|s| &**s).collect();
        Self {
            text_probe: NSArray::from_slice(&[&*text]),
            markers: NSArray::from_slice(&marker_refs),
            text,
        }
    }
}

thread_local! {
    static UTIS: Utis = Utis::new();
}

/// `NSPasteboard`-backed clipboard source.
///
/// Holds no Cocoa objects: the general pasteboard is a cheap singleton
/// lookup performed inside each poll's autorelease pool, which keeps this
/// type unconditionally `Send` for the poll task.
pub struct MacOsClipboard {
    tracker: ChangeTracker,
    rejected_too_large: u64,
}

impl MacOsClipboard {
    pub fn new() -> Self {
        Self {
            tracker: ChangeTracker::new(),
            rejected_too_large: 0,
        }
    }
}

impl ClipboardSource for MacOsClipboard {
    fn poll(&mut self) -> Option<Capture> {
        // I-17: one autorelease pool around the entire Cocoa interaction.
        // Without it, autoreleased NSString/NSData accumulate on the async
        // worker thread and reserved memory grows without bound.
        autoreleasepool(|_pool| {
            let pb = unsafe { NSPasteboard::generalPasteboard() };

            // I-1: the change-count comparison is the first thing we do; an
            // unchanged pasteboard performs zero reads and zero allocations.
            let count = unsafe { pb.changeCount() } as i64;
            match self.tracker.observe(count) {
                Change::Unchanged => return None,
                Change::SelfWrite => {
                    debug!(change_count = count, "suppressed our own pasteboard write");
                    return None;
                }
                Change::Fresh { lost_intermediates } => {
                    if lost_intermediates > 0 {
                        // §3.1/§3.2: telemetry only. NSPasteboard keeps no
                        // history, so the intermediates are gone — but the
                        // surviving value is captured below, never replaced
                        // by a "burst happened" result.
                        warn!(
                            lost = lost_intermediates,
                            change_count = count,
                            "pasteboard burst: intermediate values are irrecoverable"
                        );
                    }
                }
            }

            // I-5 / §3.4: probe the opt-out markers BEFORE reading any
            // representation, so a password never enters process memory at
            // all. "Read then discard" is not compliant. A pasteboard
            // carrying a marker *and* a normal string is dropped entirely;
            // that is intentional.
            let marked =
                UTIS.with(|utis| unsafe { pb.availableTypeFromArray(&utis.markers).is_some() });
            if marked {
                // I-9: no content, no type name.
                debug!(
                    change_count = count,
                    "pasteboard change carries an org.nspasteboard.* opt-out marker; dropped"
                );
                return None;
            }

            // I-11: text is the highest-priority representation. Image and
            // file capture are not implemented yet; when they are, they go
            // below this branch, and image *presence* must be probed
            // without materialising the bytes (I-12).
            let data = UTIS.with(|utis| unsafe {
                if pb.availableTypeFromArray(&utis.text_probe).is_none() {
                    return None;
                }
                pb.dataForType(&utis.text)
            })?;

            // I-18 (CopyPaste-1f5c): `length` is a field read, `to_vec` on a
            // multi-GiB item is a multi-GiB allocation. Check first.
            let len = unsafe { data.length() };
            if len > MAX_TEXT_BYTES {
                self.rejected_too_large += 1;
                // I-39 / §6.5: counted, not silently dropped.
                warn!(
                    bytes = len,
                    cap = MAX_TEXT_BYTES,
                    "pasteboard text exceeds the size cap; dropped"
                );
                return None;
            }

            let bytes = unsafe { data.bytes() }.to_vec();
            // public.utf8-plain-text is UTF-8 by definition; malformed input
            // is a third-party app's bug. §3.6's precedent is lossy
            // conversion rather than dropping the user's copy, and I-37
            // forbids panicking on a malformed payload.
            let content = String::from_utf8_lossy(&bytes).into_owned();
            if content.is_empty() {
                return None;
            }
            Some(Capture::text(content))
        })
    }

    fn set_contents(&mut self, text: &str) -> anyhow::Result<()> {
        // I-17 again: the paste-back path needs the pool as much as the poll.
        autoreleasepool(|_pool| {
            let pb = unsafe { NSPasteboard::generalPasteboard() };
            let pre = unsafe { pb.changeCount() } as i64;

            // §3.3 step 2: pre-stamp `pre + 2` BEFORE touching the
            // pasteboard. Stamping afterwards leaves a window in which a
            // poll records the item we just pasted as a fresh capture.
            self.tracker.sentinel.arm(pre);

            let value = NSString::from_str(text);
            let ok = UTIS.with(|utis| unsafe {
                // clearContents (+1) then setString:forType: (+1) = the
                // expected delta of 2.
                let _ = pb.clearContents();
                pb.setString_forType(&value, &utis.text)
            });
            if !ok {
                // §3.3 step 5.
                self.tracker.sentinel.clear();
                // I-9 / CLAUDE.md rule 4: no paths, no content.
                return Err(anyhow::anyhow!("the pasteboard rejected the write"));
            }

            // §3.3 step 4 (CopyPaste-8yzf): conditional post-stamp. If a
            // third-party app wrote between our `setString` and this read,
            // `actual > pre + 2`, and storing it would suppress *their*
            // content as if it were ours.
            let actual = unsafe { pb.changeCount() } as i64;
            self.tracker.sentinel.confirm(pre, actual);
            if actual != pre + SELF_WRITE_DELTA {
                debug!(
                    expected = pre + SELF_WRITE_DELTA,
                    actual, "another app wrote to the pasteboard during our write"
                );
            }
            Ok(())
        })
    }

    fn backend_name(&self) -> &'static str {
        "nspasteboard"
    }

    fn rejected_too_large_count(&self) -> u64 {
        self.rejected_too_large
    }

    fn lost_intermediates_count(&self) -> u64 {
        self.tracker.lost_intermediates
    }
}
