//! `ClipboardMonitor`: polls NSPasteboard (macOS) for text/image/file
//! changes and returns a [`ClipboardContent`] variant per poll.

// l07l: AtomicI64/Ordering are only exercised by the macOS pasteboard
// change-count path; allow them unused on non-macOS so -D warnings stays green.
#[cfg_attr(not(target_os = "macos"), allow(unused_imports))]
use std::sync::atomic::{AtomicI64, Ordering};
use std::sync::Arc;

use super::content::{ClipboardContent, ClipboardError, SKIPPED_BATCH_THRESHOLD};
#[cfg_attr(not(target_os = "macos"), allow(unused_imports))]
use super::macos_util::{log_unsupported_once, mime_from_path, percent_decode_path};

pub struct ClipboardMonitor {
    last_change_count: i64,
    max_text_bytes: u64,
    /// Maximum raw image bytes accepted from NSPasteboard before the READ gate
    /// rejects the image.  Defaults to [`copypaste_core::MAX_IMAGE_BYTES`]
    /// (10 MiB) when constructed via [`ClipboardMonitor::new`]; the daemon
    /// overrides this with the user-configured `max_image_size_bytes` so the
    /// READ gate matches the encode gate rather than the hardcoded core const.
    max_image_bytes: usize,
    /// Maximum raw file bytes accepted from a `public.file-url` clipboard entry
    /// before the READ gate rejects the file. Defaults to
    /// [`copypaste_core::MAX_FILE_BYTES`] (100 MiB); the daemon overrides this
    /// with `AppConfig::max_file_size_bytes` so the READ gate matches the encode
    /// gate rather than the hardcoded core const.
    max_file_bytes: usize,
    /// changeCount recorded after a daemon self-write to NSPasteboard (copy_item /
    /// "copy" IPC handler). When the next poll sees this exact changeCount the daemon
    /// caused the change itself — skip recording to prevent a duplicate row.
    /// Shared with `write_to_pasteboard` via an `Arc<AtomicI64>`.
    pub self_write_change_count: Arc<AtomicI64>,
}

/// CopyPaste-pbre: process-wide cache of the invariant pasteboard UTI strings.
///
/// `poll()` ran on every changed tick and called `NSString::from_str(...)` for
/// each constant UTI (the three `org.nspasteboard.*` markers, `public.png`,
/// `public.tiff`, the two file-URL types, and the five "unsupported" probes),
/// heap-allocating a fresh Cocoa string each time. These UTIs never change, so
/// we build each `Retained<NSString>` exactly once and reuse it. `NSString` is
/// `Send + Sync` (immutable Cocoa string), so a `LazyLock<Retained<NSString>>`
/// static is sound. These are strong references owned by the static, so they
/// are NOT placed in the per-tick autorelease pool.
#[cfg(target_os = "macos")]
mod pb_uti {
    use objc2::rc::Retained;
    use objc2_foundation::NSString;
    use std::sync::LazyLock;

    macro_rules! cached_uti {
        ($name:ident, $uti:literal) => {
            pub static $name: LazyLock<Retained<NSString>> =
                LazyLock::new(|| NSString::from_str($uti));
        };
    }

    cached_uti!(TRANSIENT, "org.nspasteboard.TransientType");
    cached_uti!(CONCEALED, "org.nspasteboard.ConcealedType");
    cached_uti!(AUTOGEN, "org.nspasteboard.AutoGeneratedType");
    cached_uti!(PNG, "public.png");
    cached_uti!(TIFF, "public.tiff");
    cached_uti!(FILE_URL, "public.file-url");
    cached_uti!(FILENAMES, "NSFilenamesPboardType");

    /// The five "unsupported kind" probes, paired with their label, so the poll
    /// loop can iterate cached strings instead of re-allocating each tick.
    pub static UNSUPPORTED_PROBES: LazyLock<[(&'static str, Retained<NSString>); 5]> =
        LazyLock::new(|| {
            [
                ("public.rtf", NSString::from_str("public.rtf")),
                ("public.rtfd", NSString::from_str("public.rtfd")),
                ("public.html", NSString::from_str("public.html")),
                ("public.url", NSString::from_str("public.url")),
                (
                    "com.apple.pasteboard.promised-file-url",
                    NSString::from_str("com.apple.pasteboard.promised-file-url"),
                ),
            ]
        });
}

impl ClipboardMonitor {
    pub fn new(max_text_bytes: u64) -> Self {
        use copypaste_core::{MAX_FILE_BYTES, MAX_IMAGE_BYTES};
        Self {
            last_change_count: -1,
            max_text_bytes,
            max_image_bytes: MAX_IMAGE_BYTES,
            max_file_bytes: MAX_FILE_BYTES,
            self_write_change_count: Arc::new(AtomicI64::new(-1)),
        }
    }

    /// Override the image-size READ gate with the user-configured cap.
    /// Call this after [`ClipboardMonitor::new`] when a non-default cap is set.
    pub fn set_max_image_bytes(&mut self, bytes: usize) {
        self.max_image_bytes = bytes;
    }

    /// Override the file-size READ gate with the user-configured cap.
    /// Call this after [`ClipboardMonitor::new`] when a non-default cap is set.
    pub fn set_max_file_bytes(&mut self, bytes: usize) {
        self.max_file_bytes = bytes;
    }

    /// Override the text-size READ gate with the user-configured cap.
    ///
    /// The daemon poll loop pushes the live `max_text_size_bytes` here each tick
    /// so raising/lowering the cap via `set_config` takes effect without a
    /// restart (the monitor's gate would otherwise keep its startup snapshot).
    pub fn set_max_text_bytes(&mut self, bytes: u64) {
        self.max_text_bytes = bytes;
    }

    /// Poll for new clipboard content. Returns `Some` only if the pasteboard changed.
    ///
    /// Priority: text > image (PNG/TIFF) > file (public.file-url).
    /// Image data and file data are returned as raw bytes for downstream
    /// compression + encryption.
    ///
    /// Edge cases handled (Wave 2.1):
    /// - **Rapid changes (#5):** if the changeCount delta is ≥
    ///   [`SKIPPED_BATCH_THRESHOLD`], we cannot recover intermediate values
    ///   but emit telemetry; consumers can poll again immediately to drain.
    /// - **Mixed text+image (#6):** text wins; an INFO log records that an
    ///   image was silently dropped on that poll.
    /// - **Unsupported types (#7):** RTF / custom UTIs are logged once per
    ///   kind, never silently dropped. `public.file-url` is now handled.
    pub fn poll(&mut self) -> Result<Option<ClipboardContent>, ClipboardError> {
        #[cfg(target_os = "macos")]
        {
            use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
            use objc2_foundation::{NSArray, NSData};

            // Drain the autorelease pool at the end of every poll. Without
            // this, each NSPasteboard read leaks autoreleased Cocoa objects
            // (NSString, and multi-MB image NSData) that are never freed on
            // this tokio thread, blowing up reserved virtual memory.
            let read = objc2::rc::autoreleasepool(|_pool| {
                let pb = unsafe { NSPasteboard::generalPasteboard() };
                let count = unsafe { pb.changeCount() } as i64;

                // changeCount-first: if the pasteboard is unchanged, return
                // before touching any stringForType/dataForType so an idle
                // clipboard allocates nothing. `None` signals "unchanged".
                if count == self.last_change_count {
                    return None;
                }

                // org.nspasteboard SKIP (Maccy parity / security):
                // Password managers and other privacy-aware apps annotate their
                // copies with one of three transient-/concealed-/auto-generated
                // UTIs so clipboard managers know to skip them.  We probe for
                // all three BEFORE reading any content so we never store or even
                // buffer a password-manager secret. When any of the markers is
                // present we advance `last_change_count` (so the item is not
                // re-offered on the next poll) and return `None`.
                // Reference: http://nspasteboard.org
                let nspb_skip = {
                    // CopyPaste-pbre: reuse the process-wide cached UTI strings
                    // instead of allocating three fresh NSStrings every tick.
                    let probes = NSArray::from_id_slice(&[
                        pb_uti::TRANSIENT.clone(),
                        pb_uti::CONCEALED.clone(),
                        pb_uti::AUTOGEN.clone(),
                    ]);
                    unsafe { pb.availableTypeFromArray(&probes) }.is_some()
                };
                if nspb_skip {
                    tracing::debug!(
                        change_count = count,
                        "clipboard: org.nspasteboard marker detected — skipping \
                         (transient/concealed/auto-generated)"
                    );
                    // Signal to the outer code that this changeCount should be
                    // advanced (skipped) but no content stored.  We return a
                    // sentinel tuple with `nspb_skip = true`.
                    return Some((count, None, None, None, false, vec![], true));
                }

                // CopyPaste-pbre: reuse the cached image-UTI strings.
                let png_type = &*pb_uti::PNG;
                let tiff_type = &*pb_uti::TIFF;

                // Text
                let text = unsafe {
                    pb.stringForType(NSPasteboardTypeString)
                        .map(|ns| ns.to_string())
                };

                // Probe image presence WITHOUT copying the bytes: ask the
                // pasteboard whether any image type is available rather than
                // materialising the (potentially multi-MB) NSData (#6).
                let image_types =
                    NSArray::from_id_slice(&[(*png_type).clone(), (*tiff_type).clone()]);
                let image_present = unsafe { pb.availableTypeFromArray(&image_types) }.is_some();
                let had_image_alongside_text = text.is_some() && image_present;

                // Only materialise image bytes when text is absent and an
                // image is actually present.
                let image_bytes: Option<Vec<u8>> = if text.is_none() && image_present {
                    let png_data = unsafe { pb.dataForType(png_type) };
                    // 1f5c: check NSData.len() BEFORE calling .bytes().to_vec() so
                    // a multi-GiB pasteboard image never gets fully copied into the
                    // Rust heap — NSData already owns the memory; `.len()` is a single
                    // field read with no allocation.  On size overage we skip the
                    // copy; the post-read gate (below) would have rejected it anyway.
                    if let Some(ref d) = png_data {
                        if d.len() > self.max_image_bytes {
                            None // too large — skip the copy
                        } else {
                            Some(d.bytes().to_vec())
                        }
                    } else {
                        let tiff_data = unsafe { pb.dataForType(tiff_type) };
                        tiff_data.as_deref().and_then(|d: &NSData| {
                            if d.len() > self.max_image_bytes {
                                None // too large — skip the copy
                            } else {
                                Some(d.bytes().to_vec())
                            }
                        })
                    }
                } else {
                    None
                };

                // File-URL branch: probe `public.file-url` only when text and
                // image are both absent, to keep priority text > image > file.
                // `stringForType` returns the file URL as a string (e.g.
                // "file:///Users/alice/doc.pdf"). We resolve it to a path, read
                // the bytes, and derive the filename + MIME from the path.
                // `NSFilenamesPboardType` is the legacy (pre-UTI) name for the
                // same data; we probe it as a fallback.
                let file_content: Option<(std::path::PathBuf, String, String)> = if text.is_none()
                    && image_bytes.is_none()
                {
                    // CopyPaste-pbre: reuse the cached file-URL UTI strings.
                    let file_url_type = &*pb_uti::FILE_URL;
                    let filenames_type = &*pb_uti::FILENAMES;

                    // Primary path: `public.file-url` (modern UTI).
                    // `stringForType` returns the file URL as a string like
                    // "file:///Users/alice/doc.pdf". We strip the "file://"
                    // scheme and percent-decode the path.
                    let file_path_from_url: Option<std::path::PathBuf> = unsafe {
                        pb.stringForType(file_url_type)
                            .map(|s| s.to_string())
                            .and_then(|url_str| {
                                let raw = url_str
                                    .strip_prefix("file://")
                                    .unwrap_or(url_str.as_str());
                                let decoded = percent_decode_path(raw);
                                let p = std::path::PathBuf::from(&decoded);
                                if p.is_absolute() {
                                    Some(p)
                                } else {
                                    tracing::debug!(
                                        url = %url_str,
                                        "clipboard: public.file-url is not a local absolute path — skipping"
                                    );
                                    None
                                }
                            })
                    };

                    // Fallback path: `NSFilenamesPboardType` (pre-UTI legacy).
                    //
                    // CopyPaste-q5ab: `NSFilenamesPboardType` stores a binary
                    // plist NSArray of absolute POSIX path strings — NOT a
                    // "file://…" URL string.  Calling `stringForType` on it
                    // returns nil (binary plist is not a plain string), so the
                    // old `stringForType` → strip("file://") fallback silently
                    // discarded every file copied from Finder or dragged into
                    // the clipboard.
                    //
                    // Fix: use `dataForType` to get the raw plist bytes and
                    // parse them with the `plist` crate into a `Vec<String>`.
                    // Take the first path (single-file case; multi-file drag is
                    // a separate feature).  The plist array contains plain
                    // absolute POSIX paths — no "file://" scheme, no percent
                    // encoding — so the path is used directly.
                    let file_path_from_filenames: Option<std::path::PathBuf> = if file_path_from_url
                        .is_none()
                    {
                        let maybe_bytes: Option<Vec<u8>> =
                            unsafe { pb.dataForType(filenames_type).map(|d| d.bytes().to_vec()) };
                        maybe_bytes.and_then(|bytes| {
                                match plist::from_bytes::<Vec<String>>(&bytes) {
                                    Ok(paths) => {
                                        // Take the first path that is absolute.
                                        paths.into_iter().find_map(|s| {
                                            let p = std::path::PathBuf::from(&s);
                                            if p.is_absolute() {
                                                Some(p)
                                            } else {
                                                tracing::debug!(
                                                    path = %s,
                                                    "clipboard: NSFilenamesPboardType path is not absolute — skipping"
                                                );
                                                None
                                            }
                                        })
                                    }
                                    Err(e) => {
                                        tracing::debug!(
                                            error = %e,
                                            "clipboard: NSFilenamesPboardType plist parse failed — skipping"
                                        );
                                        None
                                    }
                                }
                            })
                    } else {
                        None
                    };

                    let resolved_path = file_path_from_url.or(file_path_from_filenames);
                    resolved_path.map(|path| {
                        let filename = path
                            .file_name()
                            .map(|n| n.to_string_lossy().into_owned())
                            .unwrap_or_else(|| "file".to_string());
                        // Best-effort MIME from file extension; fall back to
                        // application/octet-stream for unknown extensions.
                        let mime = mime_from_path(&path);
                        // Return a FileRef instead of reading the bytes here.
                        // The actual std::fs::read runs in handle_tick via
                        // tokio::task::spawn_blocking so this tokio worker
                        // thread is not blocked on potentially large I/O.
                        (path, filename, mime)
                    })
                } else {
                    None
                };

                // Detect unsupported types — only matters when we have
                // nothing else to surface (text + image + file all absent).
                // We probe a fixed allowlist of common unsupported UTIs
                // rather than enumerating `pb.types()` so we don't need
                // the `NSEnumerator` feature on objc2-foundation 0.2.
                // `public.file-url` is now handled above; keep other types here.
                let mut unsupported_kinds: Vec<String> = Vec::new();
                if text.is_none() && image_bytes.is_none() && file_content.is_none() {
                    // CopyPaste-pbre: iterate the process-wide cached probe
                    // NSStrings instead of allocating one per kind every tick.
                    for (label, ns_kind) in pb_uti::UNSUPPORTED_PROBES.iter() {
                        let present = unsafe {
                            pb.dataForType(ns_kind).is_some() || pb.stringForType(ns_kind).is_some()
                        };
                        if present {
                            unsupported_kinds.push((*label).to_string());
                        }
                    }
                }

                Some((
                    count,
                    text,
                    image_bytes,
                    file_content,
                    had_image_alongside_text,
                    unsupported_kinds,
                    false, // nspb_skip: not set on the normal content path
                ))
            });

            // Unchanged pasteboard — nothing read, nothing allocated.
            let Some((
                count,
                text,
                image_bytes,
                file_content,
                had_image_alongside_text,
                unsupported_kinds,
                nspb_skip,
            )) = read
            else {
                return Ok(None);
            };

            // org.nspasteboard skip: advance the cursor but produce no content.
            if nspb_skip {
                self.last_change_count = count;
                return Ok(None);
            }

            // Self-write suppression (fix DUP-ON-COPY): when the daemon itself
            // wrote to the pasteboard (copy_item / "copy" handler), the next
            // poll will see a changeCount increment caused by our own write.
            // We must advance `last_change_count` (so we don't re-fire on the
            // same count on the *next* poll) but must NOT record the content —
            // the existing item was already promoted to the top of history by
            // `bump_item_recency`. Clear the sentinel after consuming it.
            let self_write_cc = self.self_write_change_count.load(Ordering::Acquire);
            if self_write_cc >= 0 && count == self_write_cc {
                self.last_change_count = count;
                // Consume the sentinel — only suppress once per self-write.
                self.self_write_change_count.store(-1, Ordering::Release);
                tracing::debug!(
                    change_count = count,
                    "clipboard: skipping self-write (copy_item/copy handler wrote this change)"
                );
                return Ok(None);
            }

            // Compute delta BEFORE we update the cursor. On first poll
            // (sentinel -1) we suppress the burst signal.
            let delta = if self.last_change_count < 0 {
                1
            } else {
                count - self.last_change_count
            };
            self.last_change_count = count;

            if delta >= SKIPPED_BATCH_THRESHOLD {
                let missed = (delta - 1) as usize;
                // CRITICAL fix: do NOT return SkippedBatch here and discard the
                // already-read content. The old code called:
                //   self.last_change_count = count   (line above)
                //   return Ok(Some(SkippedBatch))    ← early return
                // This caused the NEXT poll to see count == last_change_count → None,
                // permanently losing the most-recent clipboard item. Instead we log
                // the burst as a telemetry side-channel and fall through so the
                // content path below captures the current pasteboard value.
                tracing::info!(
                    delta,
                    missed,
                    "clipboard: rapid changes detected — {} intermediate updates lost \
                     (most-recent item still captured)",
                    missed
                );
                // Intentional fall-through: do not return here.
            }

            if had_image_alongside_text {
                tracing::info!("clipboard had text+image; text wins (image dropped this poll)");
            }

            if let Some(text) = text {
                if text.len() as u64 > self.max_text_bytes {
                    return Err(ClipboardError::TooLarge {
                        max: self.max_text_bytes,
                        actual: text.len(),
                    });
                }
                return Ok(Some(ClipboardContent::Text(text)));
            }

            if let Some(bytes) = image_bytes {
                if bytes.len() > self.max_image_bytes {
                    return Err(ClipboardError::ImageTooLarge {
                        max: self.max_image_bytes,
                        actual: bytes.len(),
                    });
                }
                return Ok(Some(ClipboardContent::Image(bytes)));
            }

            if let Some((path, filename, mime)) = file_content {
                // The size gate will be applied after spawn_blocking reads
                // the bytes in handle_tick. Return FileRef here so the
                // tokio worker is not blocked on potentially large I/O.
                return Ok(Some(ClipboardContent::FileRef {
                    path,
                    filename,
                    mime,
                }));
            }

            // No supported content — log any unknown kinds once each.
            for kind in unsupported_kinds {
                log_unsupported_once(&kind);
            }

            Ok(None)
        }
        #[cfg(not(target_os = "macos"))]
        {
            let _ = self.max_text_bytes;
            Ok(None)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clipboard_monitor_new_starts_with_sentinel() {
        let m = ClipboardMonitor::new(1024);
        assert_eq!(m.last_change_count, -1);
    }

    /// edge HIGH #5 — rapid_change_skip_batch_logs.
    /// We can't drive NSPasteboard from a unit test, so we verify the
    /// surrounding logic instead: when the synthetic delta is at/above
    /// threshold the monitor would emit `SkippedBatch(delta - 1)`.
    #[test]
    fn rapid_change_skip_batch_logs() {
        // Simulate the same delta arithmetic poll() uses.
        let prev: i64 = 10;
        let curr: i64 = 15;
        let delta = curr - prev;
        assert!(delta >= SKIPPED_BATCH_THRESHOLD);
        let missed = (delta - 1) as usize;
        let evt = ClipboardContent::SkippedBatch(missed);
        match evt {
            ClipboardContent::SkippedBatch(n) => assert_eq!(n, 4),
            _ => panic!("expected SkippedBatch"),
        }
    }
}
