import org.gradle.api.tasks.Exec

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

// ---------------------------------------------------------------------------
// cargo-ndk: compile Rust .so libraries for Android targets
// ---------------------------------------------------------------------------
val cargoNdkAvailable: Boolean by lazy {
    try {
        val result = ProcessBuilder("cargo", "ndk", "--version")
            .redirectErrorStream(true)
            .start()
            .waitFor()
        result == 0
    } catch (_: Exception) {
        false
    }
}

// Root of the Cargo workspace (two levels above android/app/)
val workspaceRoot: String = rootProject.projectDir.parentFile.absolutePath

val buildCargoNdk by tasks.registering(Exec::class) {
    group = "build"
    description = "Compile copypaste-android into .so libraries via cargo-ndk"

    doFirst {
        if (!cargoNdkAvailable) {
            throw GradleException(
                """
                cargo-ndk is not installed or not on PATH.
                To install: cargo install cargo-ndk
                Then add Android NDK targets:
                  rustup target add aarch64-linux-android
                  rustup target add x86_64-linux-android
                Alternatively, build manually:
                  make android-so
                Or skip native libs for a UI-only build.
                """.trimIndent()
            )
        }
    }

    workingDir(workspaceRoot)
    commandLine(
        "cargo", "ndk",
        "-t", "arm64-v8a",
        "-t", "x86_64",
        "-o", "android/app/src/main/jniLibs",
        "build",
        "-p", "copypaste-android"
    )
}

// Wire cargo-ndk before every assembleDebug/assembleRelease
tasks.whenTaskAdded {
    if (name == "assembleDebug" || name == "assembleRelease") {
        dependsOn(buildCargoNdk)
    }
}

android {
    namespace = "com.copypaste.android"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.copypaste.android"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "0.1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"))
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    sourceSets {
        getByName("main") {
            jniLibs.srcDirs("src/main/jniLibs")
        }
    }
}

dependencies {
    implementation(libs.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.kotlinx.coroutines.android)
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
    implementation("androidx.recyclerview:recyclerview:1.3.2")
    // UniFFI generated bindings (source generated by build-android.sh)
    // implementation(files("libs/copypaste_android.jar"))
}
